// =============================================
// CMA FINAL - PAPER 13
// =============================================

const PN13_CHAPTERS = [
  "Company Law - Formation, Types & Foreign Companies",
  "Share Capital, Deposits & Debentures",
  "Directors, KMP & Board Composition",
  "Audit, Accounts, Dividend & NFRA",
  "Board Meetings, Governance Procedure",
  "Mergers, Oppression & NCLT",
  "Insolvency & Bankruptcy Code",
  "Corporate Governance & CSR",
  "SEBI, Capital Markets & Competition Act",
  "FEMA & Foreign Investment",
  "Banking Regulation",
  "Insurance Law (IRDA)",
  "MSME",
  "IT Act & Cyber Law",
  "PMLA & Financial Intelligence",
];

const PN13 = [
{ c:0, q:"How many minimum members are required to form a public limited company?", o:["3", "4", "6", "7"], a:3 },
{ c:0, q:"In order to be a Govt. Company, 51% shares shall be held by: -", o:["Central Govt.", "State Govt.", "Both Central and State Govt. jointly", "Any or all of the above"], a:3 },
{ c:0, q:"In case of \"limited\" companies, what is limited?", o:["Shares", "Liability of members", "Capital of the company", "Powers of the shareholders"], a:1 },
{ c:0, q:"Restriction in transfer of shares can be there in", o:["Private Ltd. company", "Public Ltd. Company", "Govt. company", "Unlimited company"], a:0 },
{ c:0, q:"Foreign company is a company, registered out of India and", o:["Having a place of business in India", "Conducts any business in India", "Need not have any business in India", "Either (1) or (2)"], a:3 },
{ c:0, q:"Company which do not have any significant accounting transaction is called", o:["Asocial Company", "Non-functional company", "Dormant company", "Sleeping company"], a:2 },
{ c:11, q:"Life Insurance Corporation is:", o:["A statutory corp. but not PFI", "A statutory corp. and PFI", "Govt. Company", "None of the above"], a:1 },
{ c:0, q:"Persons who sign the MOA are called:", o:["Promoters", "Shareholders", "Subscribers to MOA", "Members"], a:2 },
{ c:0, q:"Certificate of incorporation is issued by: -", o:["Regional director", "Registrar of companies", "Central Govt.", "None of the above"], a:1 },
{ c:0, q:"Declaration by professional at the time of incorporation of a company means declaration by", o:["Practicing CS", "Practicing CA", "Practicing CMA", "Any of the above."], a:3 },
{ c:0, q:"Change of registered office within a city, town or village requires", o:["Special Resolution", "Board Resolution", "Approval of CG", "None of the above"], a:1 },
{ c:0, q:"Section 8 companies cannot:", o:["Generate surplus", "Make profit", "Distribute dividend", "Profit is to given to Govt."], a:2 },
{ c:0, q:"ABC Ltd. is registered in India with 100% shares being held by KYZ Ltd., a company registered in UK having no business in India. ABC Ltd. is a:", o:["An Indian Company", "Foreign company", "Wholly owned subsidiary of a foreign company but Indian Company", "Does not come under definition of foreign company"], a:0 },
{ c:2, q:"ABC Ltd. has 35% shares in XYZ Ltd. The majority of directors of XYZ Ltd. are appointed and removed by ABC Ltd. XYZ Ltd. is:", o:["Subsidiary of ABC Ltd.", "Not a subsidiary of ABC Ltd.", "Depends on Board of ABC Ltd.", "Depends on Board of XYZ Ltd."], a:0 },
{ c:0, q:"A guarantee company is similar to:", o:["Unlimited company", "LLP", "Partnership", "Sole proprietorship"], a:1 },
{ c:0, q:"Once a company is converted into LLP, intimation to ROC has to been made within:", o:["10 days", "15days.", "20days", "25 days"], a:1 },
{ c:0, q:"Which chapter of the Companies Act, 2013, deals with foreign companies?", o:["XX", "XXI", "XXII", "XXIII"], a:2 },
{ c:1, q:"In case of secured debentures of public issue, the security is created I favour of:", o:["Public", "SEBI", "Merchant banker", "Debenture trustee"], a:3 },
{ c:1, q:"Fully convertible debenture is a:", o:["debt instrument", "equity instrument", "hybrid instrument", "None of the above"], a:0 },
{ c:1, q:"Register of deposit:", o:["is voluntary", "is mandatory but particulars may vary", "is mandatory with particulars as per Rules", "Not to be maintained at all"], a:2 },
{ c:1, q:"A debenture trustee can be:", o:["Any bank", "Any NBFC", "any merchant banker", "Any entity registered with SEBI as such"], a:3 },
{ c:1, q:"\"loan\" in parlance to Companies Act, means:", o:["short term loan for revenue purpose", "long term loans", "cash credit", "working capital"], a:2 },
{ c:1, q:"In case of deposits by the company.", o:["no brokerage can be given", "any amount of brokerage can be given", "rate of brokerage shall be as per RBI Regulations", "rate of brokerage shall be as per SEBI Regulations"], a:2 },
{ c:3, q:"Once declared in AGM, dividend", o:["May be revoked", "Cannot be revoked", "May be reduced", "Payment can be delayed"], a:1 },
{ c:3, q:"IEPF stands for", o:["Investor Employment and Protection Fund", "Investor Education and Publicity Fund", "Investor Entrepreneurship and Protection", "Investor Education and Protection Fund"], a:3 },
{ c:3, q:"Once declared, the amount of dividend shall be transferred to special dividend A/c within", o:["3 days", "5 days", "10 days", "15 days"], a:1 },
{ c:3, q:"A practicing Chartered Accountant may be appointed as Auditor for term of:", o:["3 yrs", "5 yrs", "8 yrs", "10 yrs"], a:1 },
{ c:3, q:"Directors Responsibility Statement is a part of: -", o:["Annual Accounts", "Auditors Report", "Board Report", "None of the above"], a:2 },
{ c:3, q:"NFRA stands for:", o:["National Financial Reporting Authority", "National Fiscal Reporting Authority", "Non-Financial Reporting Authority", "National Financial Reforms Authority"], a:0 },
{ c:3, q:"A statutory Auditor shall be-", o:["ACS", "CMA", "Practicing CA", "Any of the above"], a:2 },
{ c:4, q:"In normal course, the Board's Report is signed by -", o:["Chairman without Authority of Board", "Chairman with Authority of Board", "MD", "Any director"], a:1 },
{ c:0, q:"CAG stands for:", o:["Controller of Audit of Govt.", "Comptroller of Auditor General", "Company Auditor General", "None of the above"], a:1 },
{ c:3, q:"The Financial statements are to be filed with the Registrar within", o:["15 days of AGM", "31st October of any year", "30 days of AGM", "60 days of AGM"], a:2 },
{ c:3, q:"In case of private company, internal auditor has to be appointed if the turnover is:", o:["Rs. 100 Crores or more", "Rs. 150 Crores or more", "Rs. 200 Crores or more", "Rs. 300 Crores or more"], a:2 },
{ c:3, q:"Auditors Report is addressed to:", o:["Board of directors", "Central Govt.", "Audit Committee", "Shareholders"], a:3 },
{ c:3, q:"CARO 2020 is effective from: -", o:["1.4.2019", "1.4.2020", "1.4.2021", "1.4.2022"], a:2 },
{ c:3, q:"First Auditor is appointed by-", o:["CG", "CAG", "Board of Directors", "Shareholders"], a:2 },
{ c:3, q:"Auditor can render the following additional service to the company where he is auditor:", o:["Internal Audit", "Accounting and book keeping", "Investment Advisory services", "None of the above"], a:3 },
{ c:2, q:"Additional director's tenure is up to", o:["Next Board meeting", "Next AGM", "5 years from the date of appointment", "Date of superannuation"], a:1 },
{ c:2, q:"Alternate director may be appointed when the additional is out of India for at least", o:["1 month", "2 months", "3 months", "4 months"], a:2 },
{ c:2, q:"A women director has to be there is the company is:", o:["A listed company", "With turnover of Rs.300 crore or more", "Either of the above", "None of the above"], a:2 },
{ c:0, q:"Section 184 of the Companies Act provides for:", o:["Ordinary", "Board", "Special", "None"], a:3 },
{ c:2, q:"A whole time director is appointed for a term of:", o:["2 yrs", "3 yrs.", "5 yrs.", "10 yrs."], a:2 },
{ c:2, q:"If a person other than retiring director is proposed, a cheque of is to be deposited with the proposal.", o:["Rs.50,000", "Rs.75,000", "Rs.1 lakh", "Rs.2 lakhs"], a:2 },
{ c:2, q:"A director may be appointed by small shareholder. Small shareholder means, shareholders who hold shares worth of face value of maximum,", o:["Rs.5,000", "Rs. 10,000", "Rs.15,000", "Rs.20,000"], a:3 },
{ c:2, q:"A company may remove a director with", o:["Board Resolution", "Ordinary resolution of shareholders", "Special Resolution of shareholders", "Approval of ROC"], a:1 },
{ c:2, q:"Managing Director's appointment is ratified in AGM through-", o:["Ordinary", "Special", "No AGM resolution is required", "None of the above"], a:0 },
{ c:0, q:"Section 203 provides for appointment of", o:["KMP", "CS", "MD", "WTD"], a:0 },
{ c:0, q:"The eligibility and conditions of appointment of MD is mentioned in Schedule", o:["I", "II", "IV", "V"], a:3 },
{ c:0, q:"Maximum remuneration to all managerial personnel is-", o:["0.05", "0.08", "0.11", "0.15"], a:2 },
{ c:2, q:"Independent directors are not entitled to get-", o:["Sitting fee", "Reimbursement of expenses", "Stock option", "Commission on profit"], a:2 },
{ c:4, q:"Board's Report is addressed to-", o:["Central Govt.", "Stock exchange", "Members", "ROC"], a:2 },
{ c:2, q:"Power of Board of directors may be restricted subject to:", o:["Companies Act", "Articles of Association", "Resolution of general meeting", "Any or all of the above"], a:3 },
{ c:4, q:"Related party transaction is provided under Schedule:", o:["188", "189", "190", "191"], a:0 },
{ c:3, q:"Majority of audit committee members shall be:", o:["Executive director", "Non-executive", "Independent", "None of the above"], a:2 },
{ c:2, q:"Independent directors, separately. shall meet in a calendar year.", o:["Once", "Twice", "Thrice", "Not meet"], a:0 },
{ c:4, q:"For Board meeting, quorum as per the Act is:", o:["One third of the total no. of directors", "Two third of the total no. of directors", "One third of the total no. of director or two, whichever is higher", "Half of the total no. of directors"], a:2 },
{ c:4, q:"If of the directors require that a resolution under circulation be placed in the Board meeting for decision, it has to be complied with.", o:["All director", "Two-third", "One-third", "Three-fourth"], a:2 },
{ c:4, q:"Minutes of the Board meeting are to be signed by-", o:["Chairman of the company", "Chairman of the present meeting or next meeting", "Chairman of the company, whether he was present in the meeting or not", "None of the above"], a:1 },
{ c:4, q:"Minutes of Board meeting are to be preserved for-", o:["5 yrs", "8 yrs", "10 yrs", "permanently"], a:3 },
{ c:4, q:"Minutes are supposed to be kept at:", o:["Registered office", "Head office", "Any office", "Any of the above"], a:0 },
{ c:4, q:"SFIO stands for", o:["Serious Fraud Institution Office", "Serious Fraud Investigating Organization", "Serious Fraud Investigating Office", "None of the above"], a:2 },
{ c:4, q:"The decision to authorize buy back by Board can be made by-", o:["Resolution by circulation", "Only in board meeting", "Any of the above", "None of the above"], a:1 },
{ c:2, q:"In case chairman is executive, at least _____ of the Board members shall be independent director.", o:["1/3rd", "2/3rd", "1/2 half", "Majority"], a:2 },
{ c:3, q:"Majority of members of the audit committee shall be-", o:["Executive directors", "Non-executive director", "Nominated director", "Independent directors"], a:3 },
{ c:2, q:"Board of directors are supposed to address their report to", o:["Central Govt.", "NCLT", "SEBI", "None of the above"], a:2 },
{ c:4, q:"The provisions relating to investigation are provided in which chapter of the Act?", o:["XIIB", "XIII", "XIV", "XV"], a:2 },
{ c:0, q:"If a company wants to punish an employee or officer of a company, it has to take permission of:", o:["ROC", "CG", "NCLT", "High Court"], a:2 },
{ c:4, q:"The investigating officer has the power of inspection, taking evidence etc. as per", o:["Civil Procedure Code", "Criminal Procedure Code", "Companies Act", "None of the above"], a:0 },
{ c:5, q:"In case of merger, the transferor company is:", o:["Continues to exist", "Dissolved", "Shall have to go through liquidation process", "Goes under the tribunal control"], a:1 },
{ c:3, q:"The Auditors has to confirm in the scheme that", o:["It is in conformity with the Accounting Standard", "It is in compliance with the Companies Act", "Both (1) and (2)", "None of the above"], a:0 },
{ c:5, q:"On amalgamation, the following are transferred to the transferee company", o:["Rights", "Liabilities", "Both above", "None of the above"], a:2 },
{ c:5, q:"When a transferor company is a listed company and transferee company is any unlisted company, the transferee company", o:["Becomes a listed company", "Continues to an unlisted company and can never be a listed company", "Continues to be an unlisted company unless it is listed by complying with listing requirement", "Any of the above"], a:2 },
{ c:0, q:"Powers of the majority is subject", o:["Companies Act", "Common law", "Memorandum of association", "All of the above"], a:3 },
{ c:2, q:"Any Act done by directors beyond authority, is considered as;", o:["unauthorized", "illegal", "ultra vires", "None of the above"], a:2 },
{ c:5, q:"A case of oppression, application may be made on:", o:["fraud on minority", "ultra vires act", "breach of duty", "Any or all of the above"], a:3 },
{ c:5, q:"Application has to be made for relief of oppression to", o:["Central Govt.", "NCLT", "ROC", "None of the above"], a:2 },
{ c:5, q:"Powers of the tribunal is listed in section:", o:["240", "241", "242", "243"], a:2 },
{ c:3, q:"Statutory auditor can also function as:", o:["Internal Auditor", "Financial Adviser", "Accounting Solutions Advisor", "Tax Auditor"], a:3 },
{ c:3, q:"A CFO of a company has to be a:", o:["Chartered accountant", "Cost accountant", "MBA", "None of the above."], a:3 },
{ c:4, q:"Sitting fee of Board meetings and Board Committee meetings:", o:["shall have to be same", "may not be same", "shall have to be different", "None of the above"], a:1 },
{ c:4, q:"Disclosure of interest by director is:", o:["one time feature at the time of appointment", "annual feature", "event based, being interested due to some event", "all or any of the above"], a:3 },
{ c:4, q:"Quorum of aboard meeting is _____ total strength of the Board:", o:["1/4th", "1/3rd", "half", "1/3rd or two whichever is higher"], a:3 },
{ c:5, q:"In case of merger of A ltd with B Ltd., A ITd is:", o:["liquidated", "dissolved", "sold", "closed down"], a:1 },
{ c:3, q:"Dividend Distribution Policy of a company is decided by:", o:["Board of directors", "shareholders in general meeting", "Stock exchange", "SEBI"], a:0 },
{ c:0, q:"Companies shall not make investment through more than _____ layer of investment companies", o:["1", "2", "3", "4"], a:0 },
{ c:1, q:"Rate of interest in deposit is guided by", o:["SEBI", "RBI", "MCA", "MOF"], a:1 },
{ c:1, q:"No eligible company shall accept or renew deposit from its members up to:", o:["0.05", "0.1", "0.15", "0.2"], a:1 },
{ c:3, q:"Interim dividend is decided by:", o:["Board of Directors", "AGM", "CMD", "Audit Committee"], a:0 },
{ c:0, q:"Books of accounts can be inspected by:", o:["MD only", "any director", "any shareholder", "any public on payment of fees"], a:1 },
{ c:3, q:"Accounting Standards are prescribed by:", o:["Central Govt", "SEBI", "Institute of Chartered Accountants of India", "None of the above"], a:0 },
{ c:4, q:"The Board Report is signed by:", o:["MD", "any director", "CS", "None of the above"], a:3 },
{ c:0, q:"Zenith Ltd. Is a company registered in USA and doing business in USA. As per Indian law, this is a:", o:["foreign company", "not a foreign company", "It will be a foreign company once it starts business in India", "both (2) and (3) is correct."], a:3 },
{ c:0, q:"A sectorial company is supposed to comply with:", o:["Companies act only", "Sectorial laws only", "Both Companies Act and sector laws", "All statements are correct"], a:2 },
{ c:0, q:"Articles of association can be altered by:", o:["Ordinary resolution", "Special resolution", "Resolution requiring special notice", "None of the above"], a:1 },
{ c:0, q:"Shifting of register office from one state to another, would require", o:["special resolution only", "special resolution and Central Govt. (CG) approval", "only CG approval", "only Board approval"], a:1 },
{ c:5, q:"The following members of a company shall have the right to apply under Section 241, for oppression namely:", o:["in the case of a company having a share capital, not less than one hundred members of the company:", "or not less than one-tenth of the total number of its members, whichever is less, or any member or members holding not less than one tenth of the issued share capital of the company,", "in the case of a company not having a share capital, not less than one-fifth of the total number of its members.", "Any of the above."], a:3 },
{ c:6, q:"The Insolvency and Bankruptcy Code passed by the Parliament in the year:", o:["2014", "2015", "2016", "2017"], a:2 },
{ c:0, q:"The Code applies to:", o:["All companies registered under Companies Act;", "LLP", "Partnership", "All of the above"], a:3 },
{ c:0, q:"An entity in favour of whom security interest is created is called:", o:["unsecured creditor", "financial creditor", "operational creditor", "secured creditor"], a:3 },
{ c:6, q:"In normal course, the corporate insolvency resolution process shall be completed within a period of _____ days from the date of admission of the application.", o:["120", "180", "210", "240"], a:1 },
{ c:0, q:"The RP has to manage the company as:", o:["Loosing concern", "Going concern", "Selling concern", "Profitable concern"], a:1 },
{ c:6, q:"As per section 22(1) The first meeting of the COC will be held within _____ days of constitution", o:["5", "6", "7", "8"], a:2 },
{ c:6, q:"A Resolution Professional may be replaced with _____ of the voting rights of the Committee of Creditors", o:["51", "66", "75", "80"], a:1 },
{ c:6, q:"The adjudicating authority in case of personal insolvency is:", o:["NCLT", "Debt Recovery Tribunal", "RBI", "SEBI"], a:1 },
{ c:6, q:"During bankruptcy proceeding, bankrupt, shall:", o:["not be appointed as trustee, public servant, election of local authority,", "not to act as director, taking part in formation of companies", "disclose in all transaction about the bankruptcy proceedings,", "all or any of the above"], a:0 },
{ c:6, q:"Under Insolvency Bankruptcy code 2016 where extension of time is requested, the Corporate Resolution process shall be completed within a period of _____ from the date of admission of the application to initiate such process.", o:["60 days", "90 days", "180 days", "240 days"], a:2 },
{ c:6, q:"Insolvency and Bankruptcy code 2016 is not applicable on:", o:["Financial Service Providers", "Partnership Firms and Individuals", "Limited Liability Partnership (LLP)", "Companies Incorporated under Companies Act"], a:0 },
{ c:0, q:"With the introduction of IB code, the following laws have been repealed:", o:["Chapter XIX and Chapter XX of Companies Act, 2013", "Part VIA, Part VII and Section 391 of Companies Act, 1956", "SICA Act, 1985", "All the above."], a:3 },
{ c:6, q:"The Insolvency and Bankruptcy Board has power of _____ Court in respect of issue of summons, discovery and production of books, inspection of books/registers and issue of commissions for examination of witnesses:", o:["Session Court", "Court", "Supreme Court", "Civil Court"], a:3 },
{ c:6, q:"The following institutions are insolvency professional agency", o:["Institute of Cost Accountants of India", "Institute of Chartered Accountants of India", "Institute of Company Secretaries", "All of them"], a:0 },
{ c:0, q:"The authority provided under the IBBI to administer and regulate the Law is:", o:["IBBI", "Insolvency professional", "Insolvency professional agency", "None of the above."], a:0 },
{ c:6, q:"Related party, in relation to a corporate debtor, means:", o:["a director or partner or a relative of a director or partner of the corporate debtor", "a key managerial personnel or a relative of a key managerial personnel of the corporate debtor;", "a limited liability partnership or a partnership firm in which a director, partner, or manager of the corporate debtor or his relative is a partner;", "all of the above"], a:3 },
{ c:6, q:"A person under IBC is:", o:["Hindu Undivided Family", "a company", "a trust", "All of the above"], a:3 },
{ c:6, q:"A person shall not be eligible to submit a resolution plan, if such person, or any other person acting jointly or in concert with such person -", o:["is an undischarged insolvent;", "is a willful defaulter of the time of submission of resolution plan,", "At the time of submission of plan, has an account, or an account of a corporate debtor under the management or control of such person or of whom such person is a promoter, classified as non-performing asset.", "All of the above"], a:3 },
{ c:7, q:"Three Ps of triple bottom line are:", o:["planet, people and purpose", "planet, people and profit", "planet, profit and purpose", "planet, profit and period"], a:1 },
{ c:7, q:"At which level corporate governance is more relevant in a company?", o:["top level", "middle level", "lower level", "all levels"], a:0 },
{ c:0, q:"which among the following would amount to undesirable practice by a senior executive of a company", o:["using published information of the competitor for his company's benefit", "using unpublished information of the competitor for his company's benefit", "using un published and secret information of the competitor obtained from undisclosed and unfair source for his company's benefit", "lure the executives of the competitor to join his company."], a:2 },
{ c:7, q:"Which, out of the following would not amount to Sustainable Development activity.", o:["rain water harvesting", "paddy cultivation", "solar energy", "plantation of sapling for forestation"], a:1 },
{ c:7, q:"corporate governance practices are almost _____ by companies in India.", o:["formalised", "regulated", "accepted", "rejected"], a:1 },
{ c:7, q:"The latest committee on Corporate governance was:", o:["Narayan Murthy committee", "Kotak committee", "Kumar Mangalam Birla committee", "Rahul Bajaj Committee"], a:1 },
{ c:7, q:"The ideal implementing agency of CSR projects, should be:", o:["section 8 company", "trust", "society", "one of the above"], a:3 },
{ c:0, q:"Economic approach to sustainability relates to:", o:["planet", "profit", "people", "none of the above"], a:1 },
{ c:7, q:"Corporate governance is more about:", o:["achieving results", "managing things", "method of managing a company", "fair method of managing a company"], a:3 },
{ c:7, q:"The items under Schedule VII of the Act, should be:", o:["strictly interpreted", "liberally interpreted", "depends on the company", "only a guideline"], a:1 },
{ c:0, q:"CG practises should target to keep balance amongst:", o:["all shareholders", "all employees", "employees and shareholders", "All stakeholders"], a:3 },
{ c:0, q:"When a company evaluates an implementing agency, first step is to", o:["local feedback", "interviewing the officials", "inspection of site", "examining documents"], a:3 },
{ c:7, q:"Every CSR activity is ultimately for the:", o:["company", "govt.", "implementing agency", "beneficiary"], a:3 },
{ c:7, q:"The CSR fund earmarked for on going project, needs to be spent within:", o:["one year", "two years", "three years", "Four years"], a:2 },
{ c:7, q:"Clause 49A which was the first major compliance of corporate governance by listed companies was on the basis of recommendation of:", o:["Narayan Murthy committee", "Kotak committee", "Kumar Mangalam Birla committee", "Rahul Bajaj Committee"], a:2 },
{ c:7, q:"Corpoarate governance is close to:", o:["ethical conduct of business", "managerial conduct of business", "target oriented business", "none of the above"], a:0 },
{ c:0, q:"A foreign entity cannot be:", o:["implementing agency of CSR project in India", "advisor", "trainer", "consultant"], a:0 },
{ c:7, q:"Some of the reasons for which companies cannot practice good governance may be:", o:["narrow mind-set of the promoters", "financial problem in the company", "unhealthy completion in the market", "or any of the above."], a:3 },
{ c:0, q:"A company sponsors the expenditure of a primary school of physically disabled students having 200 students. Three employees' children, being physical disabled, have also been admitted in that school:", o:["the school will qualify as CSR project as admission of the employees' children is incidental", "not qualify as CSR project as there are students who are employees children", "depends on how the company represents the same to the auditors", "depends on Board of Directors"], a:0 },
{ c:7, q:"Which will not qualify as CSR expenditure", o:["direct donation to a unrecognised charitable organisation", "contribution to fund under schedule VII of the Act", "any activity under schedule VII", "Direct implementation of a CSR project by the company"], a:0 },
{ c:7, q:"Advantages of direct implementation of CSR activity by the company are:", o:["Flexible, since, even small decisions also are taken by the company", "Better supervision, since it is being directly implemented", "Quick decision making", "All of the above"], a:3 },
{ c:7, q:"Advantages of third party implementation of CSR prjects, are:", o:["expertise", "Better supervision at site", "unbiased", "all of the above"], a:3 },
{ c:7, q:"CG ratings are done by:", o:["commercial banks", "RBI", "Credit Rating Agencies", "SEBI"], a:2 },
{ c:3, q:"Audit committee can:", o:["interact with statutory auditors only", "interact with internal auditors only", "interact with both statutory and internal auditors", "none if the above"], a:2 },
{ c:3, q:"The recommendation of the Audit Committee:", o:["may not be accepted by Board of Directors", "has to be accepted by Board", "In case not accepted, Board has to records the reasons", "Recommendation need not go to Board meetings"], a:2 },
{ c:7, q:"Which of the following is the advantage of the family business over non-family business?", o:["Staff recruitment", "Raising funds for growth", "Ownership vs. Management", "Deep industry insight"], a:3 },
{ c:0, q:"Maximum days for keeping an issue open is;", o:["7", "8", "9", "10"], a:3 },
{ c:0, q:"At the time of IPO, the issuer has to have a:", o:["CFO", "MD", "designated Compliance officer", "at least one independent director"], a:2 },
{ c:0, q:"Which of the flowing do not require prospects", o:["Rights issue", "Bonus issue", "IPO", "FPO"], a:1 },
{ c:1, q:"Minimum face value of shares, can be:", o:["Rs.10", "Rs. 5", "Rs. 1", "Rs. 15"], a:2 },
{ c:8, q:"Takeover means", o:["buying few shares", "acquiring 10%", "acquiring shares which will give control over the management", "none of the above"], a:2 },
{ c:8, q:"The purpose of the SEBI Act is to provide for the establishment of a Board called Securities and Exchange Board of India (SEBI). The Preamble to the Act provides for the establishment of a Board to:", o:["Protect the interests of investors in securities", "Promote the development of the securities market", "To regulate the securities market", "All of the above"], a:3 },
{ c:8, q:"SEBI has three functions rolled into one body. Which of the following is not the function of SEBI?", o:["Quasi-legislative", "Quasi-judicial", "Quasi-executive", "Quasi-official"], a:3 },
{ c:10, q:"For the appointment, reappointment, remuneration and removal of the director of a banking company, prior approval of ........................ should be obtained.", o:["Chairman", "RBI", "Managing Director", "Finance Secretary"], a:1 },
{ c:8, q:"The Competition Act has replaced-", o:["Companies Act, 1956", "Consumer Protection Act", "MRTP Act, 1969", "None"], a:2 },
{ c:0, q:"The turnover threshold for individual company, operating in India, in combination is _____ crores.", o:["Rs. 4,000", "Rs. 6,000", "Rs. 8,000", "Rs.10,000"], a:2 },
{ c:8, q:"Which is not the objective of CCI.", o:["To promote start-up company", "promote and sustain competition,", "protect the interests of the consumers", "prevent anti-competitive practices,"], a:2 },
{ c:0, q:"Selling products/services below the cost is called", o:["Undercut pricing", "Under invoicing", "Predatory pricing", "Introductory pricing"], a:2 },
{ c:8, q:"The asset bases up to US $ _____ in case of a group having presence out of India shall not be required to take CCI approval in case of merger.", o:["2 billion", "3 billion", "4 billion", "10 billion"], a:2 },
{ c:8, q:"Which of the following is not the type of unfair competition?", o:["Collusive price fixing", "Creation of barriers to entry", "Tie in purchase A", "Predatory pricing"], a:2 },
{ c:8, q:"Which of the following is not the objective of Competition Act, 2002?", o:["To prevent practices having adverse effect on competition", "To prevent competition in market", "To protect the interest of the consumers", "To ensure freedom of trade carried on by the other participant in marketing India and for matter connected there with or incidental thereto."], a:1 },
{ c:8, q:"Unfair competition under the Competition Act, 2002 means adoption of practices viz. -", o:["collusive price fixing", "allocation of markets.", "discriminatory pricing etc.", "All of the above"], a:3 },
{ c:0, q:"An association of producers, sellers or distributors, traders or service providers who, by agreement amongst themselves, limit, control or attempt to control the production, distribution, sale or price of or trade in goods or provision of services is known as", o:["Acquisition", "Agreement", "Cartel", "Pool"], a:2 },
{ c:7, q:"Which of the following is not the benefits of CSR Programme?", o:["Mutual trust", "Attracting and retaining employees", "Communities as suppliers", "Enhancing corporate reputation"], a:0 },
{ c:8, q:"Any person aggrieved by any order of Competition Appellate Tribunal (COMPAT), may file an appeal to the Hon'ble Supreme Court within... days, from the date of receipt of the order of Appellate Tribunal.", o:["30 days", "45 days", "60 days", "90 days"], a:2 },
{ c:2, q:"The Chairperson and every other Member shall hold office for a term of _____ years from the date on which he enters upon his office.", o:["2", "3", "5", "10"], a:2 },
{ c:0, q:"The Commission also has the power to impose a fine which may extend up to _____ of the total turnover or the assets of the combination, whichever is higher, for failure to give notice to the Commission of the combination", o:["0.02", "0.01", "0.005", "0.03"], a:1 },
{ c:0, q:"The Commission, may, notwithstanding anything contained in any other law for the time being in force, by order in writing, direct division of an enterprise enjoying dominant position to ensure that such enterprise does not abuse its dominant position. The order may provide for the following matters, namely:", o:["the transfer or vesting of property, rights, liabilities or obligations.", "the adjustment of contracts either by discharge or reduction of any liability or obligation or otherwise", "the creation, allotment, surrender or cancellation of any shares, stocks or securities", "all the above"], a:3 },
{ c:0, q:"If the Commission does not, on the expiry of a period of _____ days from the date of notice given to the Commission referred to in Section 29(2), pass an order or issue direction in accordance with the provisions of sub-Section (1) or (2) or (7), the combination shall be deemed to have been approved by the Commission", o:["210", "180", "260", "300"], a:0 },
{ c:9, q:"Automatic route in FDI means.", o:["Prior permission of RBI not required", "Prior permission of Central Govt, not required", "Prior permission of neither RBI nor Central Govt.is required", "None of the above"], a:2 },
{ c:9, q:"For investment in market securities, FIIs are to be registered with:", o:["Ministry of Corporate Affairs", "RBI", "SEBI", "none of the above"], a:2 },
{ c:9, q:"DPIIT comes under:", o:["Industry and Commerce", "Finance", "Corporate affairs", "none of the above."], a:0 },
{ c:0, q:"Sale of shares from a resident to non resident is:", o:["current account transaction", "capital account transaction", "any of the above", "None of the above."], a:1 },
{ c:9, q:"FDI is prohibited in the which of the following sectors:", o:["Lottery Business including Government/private lottery, online lotteries.", "Gambling and betting including casinos.", "Chit funds", "All of the above"], a:3 },
{ c:9, q:"Individuals can avail of foreign exchange facility for the following purposes within the LRS limit on financial year basis for the following:", o:["Private visits to any country (except Nepal and Bhutan)", "Gift or donation Going abroad for employment", "Emigration", "all of the above"], a:3 },
{ c:9, q:"Eligible borrower can raise up to _____ million US$ through ECB in automatic route", o:["500", "750", "1000", "1250"], a:1 },
{ c:9, q:"Total maximum remittance during a financial year under LRS scheme is:", o:["US $ 1,00,000", "US $ 1.25.000", "US $ 1,50,000", "US $ 2.50,000"], a:3 },
{ c:9, q:"The following remittance is prohibited", o:["Remittance for any purpose specifically prohibited under Schedule-I (like purchase of lottery tickets/sweep stakes, proscribed magazines, etc.) or any item restricted under Schedule II of Foreign Exchange Management (Current Account Transactions) Rules, 2000.", "Remittance from India for margins or margin calls to overseas exchanges/overseas counterparty.", "Remittances for purchase of FCCBs issued by Indian companies in the overseas secondary market", "All of the above"], a:3 },
{ c:0, q:"Zenith Ltd. is accompany registered in UK, issues shares to citizen of UK. Under the Indian law, the shares are;", o:["foreign security", "Indian security", "any of the above", "none of the above"], a:3 },
{ c:9, q:"FEMA _____ foreign currency transaction.", o:["encourages", "prohibits", "restricts", "none"], a:2 },
{ c:10, q:"NPA stands for:", o:["Non Productive asset", "Non Performance Asset", "National Productivity asset", "none of the above"], a:1 },
{ c:10, q:"Banking Regulation Act was enacted in the year:", o:["1940", "1942", "1947", "1949"], a:3 },
{ c:10, q:"Cash reserve ratio should be _____ percent of the total time and demand liabilities", o:["1", "2", "3", "4"], a:3 },
{ c:10, q:"SLR stands for:", o:["Special Liquidity Ratio", "Statutory Liquidity Reserve", "Special Liquidity Reserve", "None of the above"], a:1 },
{ c:10, q:"Banking companies cannot pay dividend unless following are completely written off.", o:["preliminary expenses", "brokerage", "commission", "all of the above"], a:3 },
{ c:10, q:"Asset Reconstruction Companies are to be registered with:", o:["SEBI", "RBI", "MCA", "none of the above"], a:1 },
{ c:10, q:"The judicial authority under SARFESI is:", o:["SEBI", "RBI", "DRT", "MCA"], a:2 },
{ c:10, q:"Amalgamation of banking companies require _____% voting of shareholders;", o:["3/4th", "One half", "two third", "One fourth"], a:2 },
{ c:10, q:"Every banking company shall maintain liquid assets not less than _____% of the total time and demand liabilities.", o:["5", "10", "20", "25"], a:3 },
{ c:10, q:"Every Banking Company incorporated in India shall prepare a balance sheet and profit and loss account as on the last working day of the -", o:["Calendar Year", "Accounting Year", "Month", "None of the above"], a:1 },
{ c:10, q:"According to Banking Regulation Act 1949, no Banking Company shall pay dividend on its shares until all its -", o:["Depreciation is fully written off.", "\"Capitalized expenses\" have been completely written off", "Bad debts are provided in full.", "Contingent liability is settled."], a:1 },
{ c:11, q:"Minimum paid up capital for a life insurance business is _____ Crore", o:["50", "75", "100", "125"], a:2 },
{ c:0, q:"Officer appointed by Central Govt. is called:", o:["IRDA", "Controller of Insurance", "Insurance Commissioner", "None of the above."], a:1 },
{ c:11, q:"in case of insurance company _____% of assets have to be remained invested in Govt. securities", o:["10", "15", "20", "25"], a:3 },
{ c:11, q:"Actuarial valuation on life insurance business has to be done once in", o:["1 years", "2 years", "3 years", "4 years"], a:0 },
{ c:11, q:"Insurance policy made by an insurer shall not be questioned after _____ years.", o:["1 years", "2 years", "3 years", "4 years"], a:2 },
{ c:11, q:"Insurance business is regulated by:", o:["SEBI", "RBI", "MCA", "none of the above"], a:3 },
{ c:11, q:"IRDA was established in the year:", o:["1999", "2000", "2001", "2002"], a:0 },
{ c:11, q:"No insurer carrying on the business of life insurance and general insurance, shall be registered unless he has minimum paid up capital of", o:["50 crores", "200 crores", "150 crores", "100 crores"], a:3 },
{ c:11, q:"The Chairman of the Insurance Regulatory and Development Authority shall hold office for a term of from the date on which he enters upon his office and should be eligible for reappointment", o:["3 years", "4 years", "5 years", "6 years"], a:2 },
{ c:11, q:"The amount credited to The Insurance Regulatory and Development Authority Fund shall consist of:", o:["all Government grants, fees and charges received by the Authority:", "all sums received by the Authority from such other source as may be decided upon by the Central Government", "the percentage of prescribed premium income received from the insurer;", "all of the above"], a:3 },
{ c:11, q:"IRDA shall, within _____ after the close of each financial year, submit to the Central Government a report giving a true and full account of its activities including the activities for promotion and development of the insurance business during the previous financial year.", o:["nine months", "three months", "one month", "six months"], a:0 },
{ c:0, q:"The principle of _____ ensures that an insured does not profit by insuring with multiple insurers.", o:["Subrogation", "Contribution", "Co-insurance", "Indemnity"], a:3 },
{ c:11, q:"An actuary is expected to:", o:["Make an exact forecast of the future liabilities of policies", "Make a reasonable forecast of the future liabilities of policies", "Calculate the premium required to cover a risk on a long-term basis", "Find the probability of an insured event to happen in non-life policies"], a:0 },
{ c:11, q:"The Insurance Laws (Amendment) Act, was passed in the year", o:["2015", "2016", "2017", "2018"], a:0 },
{ c:11, q:"the granting of superannuation allowances and benefits payable question life insurance business meaning", o:["the granting of disability and double or triple indemnity accident benefits, if so provided in the contract of insurance", "the granting of annuities upon human life, and", "the granting of superannuation allowances and benefits payable out of any fund applicable solely to the relief and maintenance of persons engaged or who have been engaged in any particular profession, trade or employment or of the dependents of such persons.", "all the above"], a:3 },
{ c:11, q:"The amount of indemnity may be limited by certain conditions which may be:", o:["Injury or loss sustained by the insured has to be proved.", "The indemnity is limited to the amount specified in the policy.", "The insured is indemnified only for the proximate causes.", "Any or all of the above."], a:3 },
{ c:11, q:"In the case of fire and motor accident insurance the insurable interest has to be present", o:["both at the time of taking the policy and at the time of the accident", "At the time of taking the policy", "At the time of happening of the event", "None of the above"], a:0 },
{ c:12, q:"NSIC stands for:", o:["National Social Institute Corporation", "National Small Institute Corporation", "National Scheme for Industries and companies", "National Small Industries Corporation."], a:3 },
{ c:12, q:"IF a unit has investment in plant an equipment of Rs.55 crore and turnover of Rs.300 crore. It will be classified as:", o:["micro", "small", "medium", "none of the above"], a:3 },
{ c:0, q:"While calculating the value of assets for ascertaining the classification, the value of the following is excluded (land/furniture).", o:["land", "furniture and fittings", "none of the above", "both of the (1) and (2)"], a:3 },
{ c:0, q:"While calculating the value of assets for ascertaining the classification, the value of the following is excluded (sales/exports).", o:["any sales", "domestic sales", "exports", "none of the above"], a:2 },
{ c:13, q:"Certifying Authority get licence to operate from:", o:["Ministry of IT", "SEBI", "Controller of Certifying Authority", "none of the above"], a:2 },
{ c:13, q:"Which among the following is not an offence under IT Act.", o:["tampering with computer source documents.", "hacking: destruction, deletion, alteration of nay data in any computer with an intention of damage/injury", "misrepresentation to controller or certifying authorities", "Controller of Certifying Authority"], a:3 },
{ c:13, q:"Information Technology (Reasonable Security Practices And Procedures And Sensitive Personal Data Or Information) Rules, was notified in the year:", o:["2011", "2012", "2013", "2014"], a:0 },
{ c:0, q:"OSBI stands for", o:["Operational source Business Inteeeligence", "Open source business Innovation", "Open source Business intelligence", "none"], a:2 },
{ c:0, q:"The key benefits that businesses can get from BI applications include the ability to:", o:["speed up and improve decision-making;", "optimize internal business processes;", "increase operational efficiency and productivity;", "all of the above"], a:3 },
{ c:13, q:"Decision of Cyber appellate Tribunal can be appealed to;", o:["High Court", "supreme Court", "None of the above", "not appealable"], a:0 },
{ c:13, q:"Information Technology (Reasonable Security Practices And Procedures And Sensitive Personal Data Or Information) Rules, 2011 apply to:", o:["only apply to bodies corporate and persons located in India.", "only apply to bodies corporate and persons located out of India.", "Apply to individuals", "All of the above"], a:0 },
{ c:13, q:"Which among the following is not a Cyber crimes under the IT Act:", o:["Tampering with Computer source documents.", "Hacking with Computer systems, Data alteration.", "Publishing obscene information", "Sending threatening messages by email"], a:3 },
{ c:13, q:"Which of the following is not an cyber Offence to Public", o:["Terrorism", "Warfare:", "Piracy", "Data alteration"], a:3 },
{ c:0, q:"Access someone's computer without the right authorization of the owner and does not disturb, alter, misuse, or damage data or system by using wireless internet connection, is called:", o:["Squatting", "Vandalism", "Hacking", "Trespass"], a:3 },
{ c:0, q:"Every reporting entity shall maintain record of:", o:["all transactions in cash of more than Rs. 10 lakhs.", "All series of integrated transaction below Rs.10 Lakh per month", "All transaction of receipt of Rs.10 lakhs and more on its equivalent foreign currency", "All of the above"], a:3 },
{ c:14, q:"FIU stands for:", o:["Financial Intelligence unit", "Financial Issue unit", "Featured Intelligence Unit", "None of the above"], a:0 },
{ c:0, q:"In part B of the schedule, offences involved a value of Rs. _____ is mentioned.", o:["15 Lakh", "50 lakh", "75 lakh", "One crore"], a:3 },
{ c:14, q:"STR stands for:", o:["Suspicious Trade Report", "Special Trade Reserve", "Suspicious Transaction Reports", "Special Trade Reports"], a:2 },
{ c:14, q:"Reporting authority shall send the KYC data to Central Registry within _____ days", o:["5", "10", "15", "20"], a:1 },
{ c:14, q:"The Money Launderer introduces the illegal funds into the financial systems. This is called:", o:["Placement", "Layering", "Integration", "None of the above"], a:0 },
{ c:14, q:"The cases under PMLA can be tried n:", o:["Common courts", "High courts only", "Special designated courts", "none of the above."], a:2 },
{ c:6, q:"Who can initiate Corporate Insolvency Resolution Process (CIRP):", o:["Only Corporate Debtor", "Financial Creditor and Operational Creditor.", "Financial Creditor, Operational Creditor and Corporate Debtor.", "Corporate Debtor and Financial Creditor."], a:2 },
{ c:6, q:"Which is the highest appellate authority in case of IBC:", o:["High Court", "Supreme Court", "National Company Law Appellate Tribunal", "Insolvency Court"], a:1 },
{ c:6, q:"In case of IBC, When is the public announcement required to be made", o:["Within 3 days of appointment of interim resolution professional.", "Within 3 days of initiating a corporate insolvency case.", "Within 3 days of admission order given by the Adjudicating Authority.", "Within 3 days of confirmation of interim resolution professional as insolvency professional."], a:0 },
{ c:6, q:"Who approves the resolution plan:", o:["Committee of creditors.", "Insolvency Professional.", "Adjudicating Authority.", "Insolvency and Bankruptcy Board of India."], a:0 },
{ c:3, q:"The OPC are allowed to file financial Statements within", o:["6 Months from the close of the financial year", "3 Months from the close of the Calender year", "3 Months from the close of the financial year", "6 Months from the close of the Calenderyear"], a:0 },
{ c:1, q:"Which of them will be considered as deposits?", o:["Money raised by issuing commercial papers", "Loans from State Bank of India", "Loan received from unrelated company", "Amount raised from unlisted unsecured NCDS"], a:3 },
{ c:1, q:"A company must execute a deposit trust deed at least _____ days before issuing the circular or circular in the form of advertisement", o:["7", "14", "21", "28."], a:0 },
{ c:1, q:"An Eligible company intending to invite deposits is required to isssue a circular in the form of an Advertisement in?", o:["DPT-4", "DPT-2", "DPT-6", "DPT-1"], a:3 },
{ c:3, q:"The Accounts of the NFRA shall be audited by", o:["CAG of India.", "Cental government", "SEBI", "RBI"], a:0 },
{ c:7, q:"Corporate Governance is a blend of the Internal and External Corporate Governance", o:["Techniques", "Mechanisms", "Systems", "Methods"], a:1 },
{ c:2, q:"The Director prepared the annual accounts in Director Responsibility Statement on a/an", o:["Money measurement basis", "Going concern basis", "Accrual basis", "Business Entity basis"], a:1 },
{ c:11, q:"A minor can be nominated as a nominee in Life Insurance Policy by its", o:["Drawer", "Agent", "Holder", "Corporation"], a:2 },
{ c:0, q:"Promoters may decide to prepare and sign a Memorandum of Understanding or Memorandum of Agreement, this is also called", o:["Articles of Association", "Memorandum of Promoters", "Promoters Agreement", "None of the above"], a:2 },
{ c:0, q:"The companies which are created by a special Act of the Legislature", o:["Registered companies", "Statutory Companies", "One Person Companies", "Limited Companies"], a:1 },
{ c:0, q:"On the Basis of Liability, in which company the liability of each member extends to the whole amount of the company's debts and liabilities but he will be entitled to claim contribution from other members.", o:["Company limited by shares", "Company limited by guarantee", "Unlimited company", "Private Company"], a:2 },
{ c:2, q:"Under OPC, The Company may have a maximum number of directors.", o:["5", "10", "15", "20"], a:2 },
{ c:0, q:"Minimum members are required to form the Public company.", o:["5", "2", "7", "10"], a:2 },
{ c:3, q:"Company which is formed and registered under this Act for a future project or to hold an asset or intellectual property and has no significant accounting transaction during the last two financial years or has not filed financial statements and annual returns during the last two financial years,", o:["Dormant Company", "Associate Company", "Nidhi Companies", "Foreign Company"], a:0 },
{ c:0, q:"The Company shall furnish to the Registrar verification of its registered office, in which Form?", o:["INC-22.", "INC-16", "INC-21", "INC-20"], a:0 },
{ c:0, q:"Under which section of the Companies Act, 2013, a memorandum is a public document?", o:["Section 326", "Section 399", "Section 346", "Section 389"], a:1 },
{ c:0, q:"Persons desirous of getting a licence under section 8, shall make an application in form?", o:["INC-9", "INC-10", "INC-12", "INC-11"], a:2 },
{ c:5, q:"Which Section, states that the transferee company shall file a copy of the scheme so approved in the manner as may be prescribed, with the Central Government, Registrar and the Official Liquidator.", o:["Section 222 (2)", "Section 233 (2)", "Section 231 (2)", "Section 223 (2)"], a:1 },
{ c:5, q:"The words \"Oppression and \"mismanagement are defined in?", o:["Section 244", "Section 241", "Section 246", "None of the above"], a:3 },
{ c:5, q:"The _____ may also file application to the Tribunal, if it is satisfied that the affairs of the company are being conducted in a manner prejudicial to the public interest", o:["Central Government", "NCLT", "Ministry of Corporate Affairs", "SEBI"], a:0 },
{ c:0, q:"What is the correct meaning of the legal term \"mutatis mutandis\"?", o:["Without any changes", "In good faith", "With mutual consent", "Subject to necessary modifications"], a:3 },
{ c:0, q:"Unlisted Companies are also called?", o:["closely held companies", "Sectoral Companies", "Associate Company", "Listed Company"], a:0 },
{ c:3, q:"The rate of dividend declared shall not exceed the average of the rates at which dividend was declared by it in the _____ years immediately preceding that year", o:["5", "4", "2", "3"], a:3 },
{ c:3, q:"The amount of the dividend, including interim dividend, shall be deposited in a scheduled bank in a separate account within _____ from the date of declaration of such dividend", o:["15Days", "5 Days", "1 month", "7 Days"], a:1 },
{ c:3, q:"The amount of dividend which have remained unclaimed and unpaid for a period of seven years from the date they became due for payment shall be credited to ?", o:["Central Govt", "SEBI", "RBI", "IEPF"], a:3 },
{ c:3, q:"In which Form the company shall send a statement of amount credited to IEPF to the authority which administer the fund.", o:["Form DIV 5", "Form DIV 2", "Form DIV 4", "Form DIV 3"], a:0 },
{ c:3, q:"The company shall also attach along with its financial statement, a separate statement containing the salient features of the financial statement of its subsidiary or subsidiaries in Form?", o:["AOC-1.", "AOC-3", "AOC-5", "AOC-2"], a:0 },
{ c:3, q:"A company shall inform the auditor concerned of his or its appointment, and also file a notice in the Form", o:["ADT-4", "ADT-1", "ADT-6", "ADT-3"], a:1 },
{ c:3, q:"Which of the following is not a type of dividend?", o:["Interim dividend", "Final dividend", "Special dividend", "Mid Term dividend"], a:3 },
{ c:10, q:"The ultimate order of winding up of a banking company in India, emerges from the", o:["order of the RBI.", "order of the Central Government.", "order of the RBI on request by the members of banking company.", "orders of the jurisdictional High Court."], a:3 },
{ c:12, q:"In the course of doing business if a MSME unit goes to next category,", o:["it shall cease to avail all the MEME benefits.", "it shall continue to avail all non-tax benefits for next 2 years.", "it shall continue to avail all non-tax benefits for next 3 years.", "it can avail only for the next one Financial year."], a:2 },
{ c:3, q:"An auditor appointed in a casual vacancy shall hold office until the conclusion of the:", o:["Next board meeting", "Next annual general meeting", "Current fiscal year", "Next extraordinary general meeting"], a:1 },
{ c:3, q:"In the case of a company whose accounts are subject to audit by an auditor appointed by the Comptroller and Auditor General of India, casual vacancy of an auditor be filled by the Comptroller and Auditor General of India within", o:["30 days.", "60 days.", "15 days.", "45 days."], a:0 },
{ c:3, q:"If the Auditor has resigned from the company, he shall file within a period of _____ from the date of resignation, a statement in the form _____ with the company and the Registrar.", o:["15days, ADT-1", "30days, ADT-3", "60days, ADT-6", "90days, ADT-4"], a:1 },
{ c:2, q:"No person shall hold the position of small shareholders director in more than _____ companies at the same time.", o:["two", "three", "four", "None of the Above"], a:0 },
{ c:0, q:"What is the maximum time within which pre-cleared trades must be executed under the Code of Conduct?", o:["3 trading days", "5 trading days", "7 trading days", "10 trading days"], a:2 },
{ c:8, q:"A hostile takeover is defined as:", o:["Takeover supported by the board of directors", "Takeover without the consent of the promoters", "Acquisition through stock exchange block deals", "Acquisition initiated with shareholder approval"], a:1 },
{ c:8, q:"In the case of connected persons, the burden of proving absence of possession of UPSI lies on:", o:["SEBI", "The Connected Person themselves", "The Board of Directors", "The Compliance Officer"], a:1 },
{ c:8, q:"What is the minimum public float that must be maintained after acquisition", o:["25%", "30%", "15%", "20%"], a:0 },
{ c:8, q:"Which of the following does not fall under the definition of \"encumbrance\" in context of disclosure?", o:["Pledge of shares", "Lien on shares", "Hypothecation of shares", "Dividend declaration"], a:3 },
{ c:8, q:"All sums realised by way of penalties under the competition Act, 2002 are credited to:", o:["Competition Fund", "Consolidated Fund of India", "Finance Account of Ministry of commerce", "PM Relief Fund"], a:1 },
{ c:8, q:"Cartel' as defined under the section 2C of the Competition Act, 2002 may take place between:", o:["Producers and Consumers", "Indian consumers and Foreign Consumers", "Workers of same sector suited in different statees", "Service providers among themselves."], a:3 },
{ c:0, q:"False statements or material omissions by a party to a combination attract a minimum penalty of:", o:["Rs. 50 lakhs", "Rs. 20 lakhs", "Rs. 1 crore", "Rs. 75 lakhs"], a:0 },
{ c:0, q:"A person resident in India may acquire foreign property without prior approval of RBI if:", o:["It was inherited from a resident Indian", "It was gifted by a friend residing abroad", "It was acquired while he was a non-resident", "He is a foreign national working in India"], a:2 },
{ c:0, q:"Schedule II of Current Account Rules relates to:", o:["Prohibited transactions", "Transactions requiring RBI prior approval", "Transactions requiring Central Govt. prior approval", "Transactions with monetary limits"], a:1 },
{ c:9, q:"A person has been maintaining an account with an Authorized Dealer bank for only 6 months. Can they remit under LRS?", o:["No, the account must be at least 1 year old", "Yes, with RBI permission", "Only for current account transactions", "Yes, for up to USD 50,000"], a:0 },
{ c:0, q:"Which non-resident entities are eligible to provide credit enhancement to domestic rupee debt instruments?", o:["All foreign banks", "Only foreign private equity investors", "Any foreign company registered with SEBI", "Multilateral financial institutions and equity holders"], a:3 },
{ c:10, q:"As per Section 19, banking companies require prior approval of RBI to:", o:["Take deposits", "Open foreign branches", "Form subsidiary companies", "Issue shares"], a:2 },
{ c:0, q:"Under what conditions can RBI apply for the winding up of a bank?", o:["Violation of minimum capital norms", "Non-compliance with licensing requirements", "Inability to pay debts", "All of the above"], a:3 },
{ c:10, q:"Asset Reconstruction Company must not have incurred losses in any of the _____ preceding financial years for registration.", o:["2", "3", "4", "5"], a:0 },
{ c:10, q:"Which of the following is a permissible measure under asset reconstruction?", o:["Payment of dividend to shareholders", "Takeover of management of borrower", "Opening new branches", "Merging with the borrower"], a:1 },
{ c:0, q:"The burden of proving proximate cause of loss lies on the:", o:["Insurance agent", "Insurer", "Policyholder", "IRDAI"], a:2 },
{ c:12, q:"The MSME Emergency Credit Line Guarantee Scheme (ECLGS) was launched primarily to:", o:["Support startups", "Address COVID-19-related liquidity needs", "Fund international ventures", "Promote rural tourism"], a:1 },
{ c:14, q:"The Prevention of Money Laundering Act, 2002 consists of ten chapters containing", o:["75 sections", "60 sections", "45 sections", "25 sections"], a:0 },
{ c:14, q:"In which Stage, the Money Launderer typically engages in a series of continuous conversions or movements of funds, within the financial or banking system by way of numerous accounts, so as to hide their true origin and to distance them from their criminal source.", o:["Placement", "Layering", "Integration", "None of the Above"], a:1 },
{ c:14, q:"In the The Prevention of Money Laundering Act, 2002, Every Scheduled Offence is a", o:["Money Laundering Offence", "Pre-requisite Offence", "punishable offence", "Predicate Offence"], a:3 },
{ c:14, q:"FIU-IND is an independent body reporting directly to the _____ headed by the Finance Minister.", o:["Economy Intelligence Court (EIC)", "Economic Intelligence Council (EIC)", "Finance Intelligence Council (FIC)", "Finance Intelligence Court (FIC)"], a:1 },
{ c:13, q:"Which section of the Information Technology Act explicitly provides that whenever a corporate body possesses or deals with any sensitive personal data or information, and is negligent in maintaining a reasonable security to protect such data or information, which thereby causes wrongful loss or wrongful gain to any person, then such body corporate shall be liable to pay damages to the person(s) so affected", o:["Section 75 A", "Section 43A", "Section 72A", "Section 42A"], a:1 },
{ c:13, q:"As per Information Technology Act, CCA stands for?", o:["Central Cybersecurity Agency", "Cyber Crime Authority", "Controller of Certifying Authority", "Central Communications Authority"], a:2 },
{ c:0, q:"Rule 3 of the 2011 Rules provides a list of items that are to be treated as", o:["sensitive personal data", "Confidential company information", "Classified government records", "General user metadata"], a:0 },
{ c:0, q:"False ATM cards i.e. Debit and Credit cards used by criminals for their monetary benefits through withdrawing money from the bank account mala-fidely.", o:["Cyber-Stalking", "Obscenity", "Spoofing:", "Carding"], a:3 },
{ c:13, q:"where two persons claim for the same Domain Name either by claiming that they had registered the name first on by right of using it before the other or using something similar to that previously. Which type of Cyber crime it is?", o:["Squatting", "Vandalism", "Trespass", "None of the above"], a:0 },
{ c:14, q:"In which year was the Central KYC Registry constituted?", o:["2012", "2015", "2017", "2020"], a:1 },
{ c:14, q:"According to the definition, a suspicious transaction:", o:["Must always be made in cash", "Can be identified only by law enforcement agencies", "Can be identified by anyone acting in good faith", "Must involve amounts above ₹50,000"], a:2 },
{ c:11, q:"Under the Insurance Regulatory and Development Authority Act, 1999, who has the right to remove difficulties or impediments by making notification in the Official Gazette?", o:["The Insurance Regulatory and Development Authority (IRDA)", "The Supreme Court of India", "The Central Government", "The Finance Ministry"], a:2 },
{ c:12, q:"When was the Ministry of Small Scale Industries and Agro and Rural Industries originally created?", o:["1997", "1999", "2001", "2003"], a:1 },
{ c:12, q:"PMEGP Scheme stands for?", o:["Prime Minister Employment Guarantee Programme", "Prime Minister Employment Generation Programme", "Public Management and Employment Growth Programme", "Prime Minister Economic Growth Plan"], a:1 },
{ c:0, q:"business intelligence tools put BI and data visualization functionality directly into business applications. That enables business users to analyze data within the applications they use to do their job.", o:["Operational intelligence", "Embedded BI", "Open source", "Collaborative"], a:1 },
{ c:0, q:"When a joint venture is formed without registering a company, it is called a:", o:["Limited joint venture", "Sole joint venture", "Merged joint venture", "Non-corporate joint venture or contractual joint venture"], a:3 },
{ c:0, q:"Which of the following is NOT allowed for a Section 8 company?", o:["Applying profits for its objectives", "Promoting education or research", "Paying dividends to its members", "Promoting environmental protection"], a:2 },
{ c:0, q:"As per Rule 38 of the Companies (Incorporation) Rules, 2014, What is SPICE+?", o:["Simplified Proforma for Incorporating Company Electronically Plus: INC-32", "Single Portal for Incorporating Companies Electronically Plus", "Special Procedure for Incorporation and Compliance electronically", "Standard Process for Incorporating Corporate Entities Plus"], a:0 },
{ c:3, q:"If the financial statements of a company do not comply with the accounting standards, what must the company disclose?", o:["Only the name of the auditor", "The deviation from the accounting standards, reasons for deviation, and financial effects of the deviation", "deviation from the accounting standards", "Only the reasons for deviation"], a:1 },
{ c:3, q:"In which section, The Directors' Responsibility Statement referred", o:["134 (3) (c)", "136(5) (a)", "140(3) (d)", "133 (b)"], a:0 },
{ c:4, q:"As per Section 134(6), The Board's report and any annexures thereto shall be signed by ?", o:["Any shareholder of the company", "The Chief Financial Officer (CFO) only", "The Company Secretary only", "The chairperson"], a:3 },
{ c:12, q:"What happened to the Ministry of Small Scale Industries and Agro and Rural Industries in September 2001?", o:["It was renamed", "It was split into two separate ministries", "It was merged with the Ministry of Commerce", "It was dissolved"], a:1 },
];
