// =============================================
// CMA FINAL - PAPER 14 (Strategic Financial Management)
// =============================================

const PN14_CHAPTERS = [
  "Investment Decisions, Project Planning and Control",
  "Evaluation of Risky Proposals for Investment Decisions",
  "Leasing Decisions",
  "Securitization",
  "Introduction (Security Analysis & Portfolio Management)",
  "Equity and Bond Valuation and Evaluation of Performance",
  "Mutual Funds",
  "Portfolio Theory and Practice",
  "Asset Pricing Theories",
  "Portfolio Performance Evaluation and Portfolio Revision",
  "Efficient Market Hypothesis",
  "Risks in Financial Market",
  "Financial Derivatives - Instruments for Risk Management",
  "The International Financial Environment",
  "Foreign Exchange Market",
  "Foreign Exchange Risk Management",
  "Digital Finance",
];

const PN14 = [
{ c:0, q:"Relevant cost analysis or relevant costing is used for various managerial decisions, like", o:["Make or buy decision", "Accepting or rejecting a special order", "Both 1 and 2", "Deciding sale quantity"], a:2 },
{ c:0, q:"Average Rate of Return (ARR) =", o:["(Average Annual Profit after Tax/Average Investment) x 100", "(Average Annual Profit after Tax/Opening Investment) x 100", "(Average Annual Profit before Tax/Average Investment) x 100", "(Average Annual Profit after Tax/Net Sales) x 100"], a:0 },
{ c:0, q:"A project with an initial investment of Rs.50 Lakh and life of 10 years, generates CFAT of Rs.10 Lakh per annum. Calculate the Payback Reciprocal.", o:["10%", "20%", "100%", "None of these"], a:1 },
{ c:0, q:"A project requires an initial investment of Rs.3,00,000. It yields annual cash inflow of Rs.60,000 for 8 years. You are required to find out the pay-back period of the project.", o:["8 years", "1 year", "5 years", "2 months"], a:2 },
{ c:0, q:"A project requires an initial investment of Rs.5,00,000. It yields annual cash inflow of Rs.1,00,000 for 8 years. You are required to find out the payback -profitability of the project.", o:["Rs.3,00,000", "Rs.1,20,000", "Rs.8,00,000", "Rs.40,00,000"], a:0 },
{ c:0, q:"NPV at discounting rate of 10% = Rs.1250 and NPV at discounting rate of 11% = Rs. (-) 200. The IRR of the proposal is", o:["11.86%", "10.86%", "9.87%", "11.96%"], a:1 },
{ c:0, q:"The Profitability Index of a project is 1.28 and its cost of investment is Rs. 2,50,000. The NPV of the project is", o:["Rs. 75,000", "Rs. 80,000", "Rs. 70,000", "Rs. 65,000"], a:2 },
{ c:0, q:"The IRR of a project is 10%. If the annual cash flow after tax is Rs.1,30,000 and project duration is 4 years, what is the initial investment in the project?", o:["Rs.4,10,000", "Rs. 4,12,100", "Rs. 3,90.000", "Rs. 4,05,000"], a:1 },
{ c:0, q:"Which of the following statements is/are true?", o:["NPV is not useful for evaluating mutually exclusive projects.", "The result of the NPV technique is not effected by the discount rate used.", "Benefit-cost ratio helps in evaluating the projects which differ in initial outlays.", "The advantage of NPV criteria is that it remains the same for all possible reinvestment rates of intermediate cash flows."], a:2 },
{ c:0, q:"Terminal value of the projects' cash inflows means", o:["The sum of the future cash flows after a particular period of time", "The present value of the projects future cash inflows", "The sum of the reinvested values of the cash inflows up to the end of the project life", "The sum of the reinvested values of the cash inflows up to the end of the project life minus initial outlay"], a:2 },
{ c:0, q:"IRR can be viewed as", o:["Desired rate of return for the investment proposed", "Rate of return earned on the initial investment", "The discount rate at which the capital is procured", "Rate of return earned on the intermediate cash flows of the project"], a:1 },
{ c:0, q:"At IRR, NPV is", o:["0", "1", "100", "-1"], a:0 },
{ c:0, q:"When NPV is zero, PI is", o:["0", "1", "100", "-1"], a:1 },
{ c:0, q:"Requirement of Social Cost Benefit Analysis is/are", o:["Monetary Cost Benefit Analysis fails to consider the external effects of a project, which may be positive like development of infrastructure or negative like pollution and imbalance in environment.", "Taxes and subsidies are monetary costs and gains, but these are only transfer payments from social point of view and therefore irrelevant.", "Market prices used to measure costs and benefits in project analysis, do not represent social values due to imperfections in market.", "All of these"], a:3 },
{ c:0, q:"Which of the following techniques is the most suitable, when NPV and IRR lead to inconsistent ranking due to life disparity between two or more projects?", o:["Modified Net Present Value.", "Modified Internal Rate of Return.", "Uniform Annual Equivalent Cost/Benefit.", "Discounted Payback Period."], a:2 },
{ c:1, q:"______ analyses investment opportunities involving a sequence of decisions over time.", o:["Decision-tree Method", "Normal Probability Distribution", "Social Cost Benefit Analysis", "None of these"], a:0 },
{ c:0, q:"Given, Investment Rs.1,00,000, Life 3 years, Annual Cash Inflows Rs.2,00,000, Annual Cash Outflows Rs. 1,50,000, Appropriate Discount Rate 10%. Calculate NPV.", o:["Rs.24,300", "Rs.23,400", "Rs.15,000", "Rs.60,000"], a:0 },
{ c:1, q:"Coefficient of variation", o:["Is an absolute measure of risk", "Is a relative measure of risk", "Is given by mean expected return by standard deviation", "Is given by the product of mean expected return and standard deviation"], a:3 },
{ c:0, q:"If nominal discounting rate is 15%, inflation rate is 5%, then real discounting rate will be", o:["9.52%", "9.25%", "10.25%", "10.52%"], a:0 },
{ c:1, q:"If expected NPV = Rs.1,20,000 and S.D = Rs.30,000 then coefficient of variation will be", o:["25%", "20%", "30.00%", "50%"], a:0 },
{ c:1, q:"Given, expected value of profit without perfect information = Rs.1,600 and expected value of perfect information = Rs.300, then expected value of profit with perfect information will be", o:["Rs.1,300", "Rs.1,900", "Rs.950", "None of these"], a:1 },
{ c:1, q:"If project cost Rs. 12,000, Annual cash flow = Rs.4,500 Cost of capital = 14%, life 4 years, PVIFA (14%, 4) = 2.9137, then the sensitivity with respect to the project cost is", o:["9.27%", "10.27%", "9.72%", "10.72%"], a:0 },
{ c:1, q:"______ is an imitation of a real-world system using a mathematical model that captures the characteristic features of the system as it encounters random events in time.", o:["Simulation", "Scenario analysis", "Sensitivity analysis", "None of these"], a:0 },
{ c:2, q:"Limitations of Leasing are", o:["The lessor generally imposes certain restrictions on the leased assets. The Lessee may not be permitted to make additions on alterations to suit his needs.", "A Financial Lease may entail a higher pay out obligation, if the equipment is not found useful subsequently, and the lessee opts for premature termination of the Lease arrangement.", "In most circumstances, the Lessee does not become the owner of the asset, and is thus deprived of the residual value of the asset.", "All of these"], a:3 },
{ c:2, q:"The major advantage of leasing is that it", o:["Provides finance without diluting ownership", "Allows use of asset without heavy initial outlay", "Offers tax benefits and flexibility", "All of the above"], a:3 },
{ c:2, q:"A finance lease is an agreement between an owner of an asset and a user of that asset wherein the:", o:["usual risks and benefits of ownership are transferred to the user", "legal title to property is transferred to the lessee when the first lease payment is made", "ownership passes to the lessor on inception date of the lease", "substantially all of the risks and benefits of ownership remain with the lessor."], a:0 },
{ c:2, q:"A way to analyse whether debt or lease financing would be preferable is to:", o:["compare the net present values under each alternative, using the cost of capital as the discount rate.", "compare the net present values under each alternative, using the after-tax cost of borrowing as the discount rate.", "compare the payback periods for each alternative.", "compare the effective interest costs involved for each alternative."], a:1 },
{ c:2, q:"Which of following clearly define the Leasing services?", o:["One party agrees to rent property owned by another party", "It guarantees the lessee, also known as the tenant, use of the asset", "It guarantees the lessor, regular payments from the lease", "All of the above"], a:3 },
{ c:2, q:"The type of lease that includes a third party, a lender, is called as which of the following?", o:["Sale and leaseback", "Leveraged Lease", "Direct leasing arrangement", "Operating lease"], a:1 },
{ c:2, q:"As per ______ plan, the periodic lease rent will go on decreasing with a specified rate of decrease.", o:["Stepped-up Plan", "Steppeddown -Plan", "Deferred Payment Plan", "Equal Periodic Plan"], a:1 },
{ c:2, q:"As per ______ plan, the periodic lease rent payable in the initial period would be less, fixed up in such a way to meet the nominal amount comparative to the cost of investment, the rest of the amount is payable in lump sum during the ending periods of the lease.", o:["Balloon Payment Plan", "Steppeddown -Plan", "Deferred Payment Plan", "Equal Periodic Plan"], a:0 },
{ c:2, q:"Which of the following is limitation of Leasing?", o:["Sale and Leaseback", "No Dilution of Ownership", "Source of Financing", "High Pay-out"], a:3 },
{ c:2, q:"Which of the following is/are the objective/s of Cross Border Leasing?", o:["reduction of overall cost of financing through utilization of tax depreciation allowances by the lessor in order to reduce its taxable income.", "Depending on the structure, in some countries, the lessor can utilize very favourable 'Leveraged Lease' Financial Accounting treatment for the overall transaction.", "The lessor is often able to utilize non-recourse debt to finance a substantial portion of the equipment cost.", "All of the above"], a:3 },
{ c:3, q:"A financial institution securitizes part of its balance sheet for ______ main reasons.", o:["3", "4", "2", "None of these"], a:0 },
{ c:3, q:"Securitization is beneficial from the view point of investors also. The potential attractions includes which of the following?", o:["Ability to diversify into sectors of exposure that might not be available in the regular bond markets (for example, residential mortgages or project finance loans)", "Access to different (and sometimes superior) risk-reward profiles", "Access to sectors that are otherwise not open to them", "All of the above"], a:3 },
{ c:3, q:"Which of the following parties is/are not involved in Securitisation?", o:["Originator", "Arranger", "Investee", "Special Purpose Vehicle"], a:2 },
{ c:3, q:"In securitization who is the issuer of securities?", o:["Originator", "SPV", "Underwriter", "Depositer"], a:1 },
{ c:3, q:"The concept of securitisation is associated with", o:["Capital market", "Money market.", "Debt market.", "Foreign exchange market."], a:2 },
{ c:3, q:"Under 'securitisation process', original borrower is known as", o:["SPV", "Obligor", "Credit enhancer", "None of these"], a:1 },
{ c:3, q:"______ certificate under securitisation have multiple maturity structure.", o:["Pass through certificate", "Pay through certificate", "Interest only certificate", "None of these"], a:1 },
{ c:4, q:"Fundamental Analysis necessiates which of the following?", o:["Economic Analysis", "Industry Analysis", "Both 1 and 2", "None of these"], a:2 },
{ c:4, q:"______ is the study and analysis of Security Price movements on the following assumptions: 1. There is a basic trend in the share price movements. 2. Such trend is repetitive. 3. Share prices have little relationship with Intrinsic Value and are based more on investor psychology and perception.", o:["Fundamental Analysis", "Technical Analysis", "Company Analysis", "None of these"], a:1 },
{ c:4, q:"______ is a measure of a country's economic activity and is defined as the total amount of goods and services produced in a country in a year", o:["Gross Domestic Product", "Business Cycles", "Growth Stocks", "Value Stocks"], a:0 },
{ c:4, q:"The major components of GDP are", o:["Consumption Spending", "Government Budget and expenditure", "Consumption in the Process of Imports Distribution", "All of these"], a:3 },
{ c:4, q:"Balance of payment can be grouped into three broad accounts, which are", o:["Trade account balance, Compulsory account balances and Capital account balance", "Total account balance, Current account balances and Capital account balance", "Trade account balance, Current account balances and Assets account balance", "Trade account balance, Current account balances and Capital account balance"], a:3 },
{ c:4, q:"Which of the following techniques are not used in Economic Analysis?", o:["Anticipatory Surveys", "Indicator Approach", "Economic Model Building Approach", "International Product Analysis"], a:3 },
{ c:4, q:"Which of the following factors are most sensitive to a firm's earnings to the business cycle?", o:["Sensitivity of sales", "Combined Leverage", "Financial Leverage", "Both 1 and 3"], a:3 },
{ c:5, q:"P/E =", o:["Stock Price/EPS", "Share Price/Book Value per Share", "Dividend /Net Income", "None of these"], a:0 },
{ c:4, q:"Which of the following techniques are used in Company Analysis?", o:["Correlation & Regression Analysis", "Time Series and Trend Analysis", "Decision Tree Analysis", "All of these"], a:3 },
{ c:4, q:"SWOT analysis involves an examination of a firm's strengths, weaknesses, opportunities and", o:["turnovers", "threats", "scopes", "objectives"], a:1 },
{ c:4, q:"Inventory Turnover Ratio =", o:["Returns from Operations/Average inventory", "Revenue from Operations/Average Net Fixed Assets", "Current Assets /Current Liabilities", "None of these"], a:0 },
{ c:4, q:"The stock price in the stock market", o:["Hovers around the support level or resistance level", "Moves between the same support and resistance levels", "Moves between the changing support and resistance level", "Both (a) and (b)"], a:2 },
{ c:5, q:"A company has an ROE of 0.24 and book value of Rs.25.38. the EPS for this company is", o:["6.09", "7.25", "6.94", "6.13"], a:0 },
{ c:4, q:"In the bull market", o:["The stock prices are increasing", "Each peak is higher than the previous peak", "Each bottom is higher than the previous bottom", "Both 2 and 3"], a:3 },
{ c:5, q:"If ROA is 0.195 and the leverage factor of 1.38, the ROE of the company is", o:["0.279", "0.283", "0.254", "0.269"], a:3 },
{ c:5, q:"MN Limited is expected to grow at the rate of 8% per annum, which currently pays Rs.10 as dividend. For investments at this risk level, investor requires a return of 15% a year, what is the estimated value of the stock?", o:["Rs.10.80", "Rs.154.29", "Rs.166.63", "None of these"], a:1 },
{ c:5, q:"A company's share is currently traded for Rs.80 per share. It is expected that a dividend of Rs.4 per share after one year will grow at 8% indefinitely. What is the expected return?", o:["8%", "13%", "5%", "80%"], a:1 },
{ c:5, q:"______ bond is issued at a discount and repaid at face value. No periodic interest is paid.", o:["Bearer Bonds", "Puttable Bonds", "Zero Coupon Bond", "Registered Bonds"], a:2 },
{ c:5, q:"______ bonds refer to the ability of the issuer to pay off a debt obligation prior to its maturity at the option of the issuer of debt.", o:["Puttable Bonds", "Term Bonds", "Perpetual Bonds", "Callable Bonds"], a:3 },
{ c:5, q:"Consider a 10 year, 12% coupon bond with a par value of Rs.10,000. Assume that the required yield on this bond is 13%. Find out the value of the bond.", o:["Rs.3.601.10", "Rs.651.10", "Rs. 2.950", "None of these"], a:0 },
{ c:5, q:"A bond with a face value of Rs. 1,000 provides 12% annual return and pays Rs.1,050 at the time of maturity, which is 10 years from now. If the investor required rate of return 13%, at which price should the company issue the bond?", o:["Rs.651.12", "Rs.309.75", "Rs.960.87", "Rs.970"], a:2 },
{ c:5, q:"Face value of a bond Rs. 1,000, coupon rate 6%, Current market Rs.900. Current Yield?", o:["6%", "6.67%", "10%", "90%"], a:1 },
{ c:5, q:"Default risk is nil in", o:["Treasury bills", "IDBI bonds", "ICICI bonds", "Reliance bonds"], a:0 },
{ c:5, q:"Value of the bond depends on", o:["Coupon rate", "Expected yield to maturity", "Years to maturity", "All of the above"], a:3 },
{ c:5, q:"By investing in bonds, a trader is subjecting himself to the following risks", o:["Interest rate risk", "Default risk", "Reinvestment risk", "All of the above"], a:3 },
{ c:5, q:"The current dividend, market price and the annual dividend growth rate of a company are Rs.2.50 per share, Rs.50 per share and 5%, respectively. The capitalization rate of the equity will be", o:["0.0526", "0.10", "0.1050", "0.1025"], a:3 },
{ c:5, q:"A company with PAT of Rs.40 Lakh, tax rate of 50%, RONW of 100%, reserves of Rs.30 lakh and a par value Rs.5 will have pre-tax EPS of", o:["Rs. 4.00", "Rs. 40.00", "Rs. 36.00", "Rs. 42.00"], a:1 },
{ c:5, q:"A stock with a dividend pay-out ratio of 45%, required rate of return is 15% and a constant growth rate of 10% will have a P/E ratio of", o:["3 times", "9 times", "8 times", "7.5 times"], a:1 },
{ c:5, q:"The current price is Rs. 100, the required rate of return is 20% and the dividend paid Rs.3.00 on a share of Rs. 10 face value. What is the expected growth rate?", o:["15%", "16%", "18%", "17%"], a:3 },
{ c:5, q:"According to the constant growth model, the next year's dividend is Rs.2.00, required rate of return is 15% and the growth rate is 10%, the market price would be", o:["Rs. 50", "Rs. 45", "Rs. 40", "Rs. 48"], a:2 },
{ c:5, q:"A Ltd. has 1 million AAA rated 12% bonds outstanding, maturity in 7 years from now. If the market interest rate is 14%, the price of the bond is (assume FV Rs. 100) and coupons are payable annually", o:["90.00", "91.46", "93.00", "94"], a:1 },
{ c:5, q:"You just purchased a 10-year maturity, semi-annual coupon bond for Rs.1,148.77 (face value Rs. 1,000), a coupon rate of 8% and a yield to maturity 6%. The bond is callable in four years at Rs. 1,080. what is the yield to call?", o:["5.60%", "6.0%", "7.2%", "8.00%"], a:3 },
{ c:5, q:"A 20-year maturity bond with a par value Rs. 1,000 makes semi-annual payments at a coupon rate of 8%. The YTM is 9%. How much should you pay for the bond?", o:["Rs.1,080", "Rs. 1,000", "Rs.908", "Rs.966"], a:2 },
{ c:6, q:"A closed-end fund has a portfolio currently worth Rs.350 million. The fund has liabilities of Rs.5 million and 17 million units outstanding. What is the net asset value of the fund?", o:["Rs.20.28", "Rs.20.29", "Rs.20.59", "Rs.29.17"], a:1 },
{ c:6, q:"If opening units 1,25,000 Units subscribe 2,00,000, Units redeem 50,000 then Closing units?", o:["3,25,000 units", "2,75,000 units", "3,75,000 units", "2.50,000 units"], a:1 },
{ c:6, q:"The important role while establishing the mutual fund scheme is played by the", o:["AMC", "Trustees", "Sponsors", "Custodians"], a:2 },
{ c:6, q:"Settlement are done at the instance of the", o:["Custodian", "AMC", "Trustees", "Sponsors"], a:1 },
{ c:6, q:"Balanced funds have the following characteristics", o:["They consist of equity and bonds in equal proportion", "They have moderate risk component", "They have above average growth potential", "None of the above"], a:1 },
{ c:6, q:"Which among the following increases the NAV of a mutual fund scheme?", o:["Value of investments", "Receivables", "Accrued income", "All of 1,2 and 3"], a:3 },
{ c:6, q:"Which of the following benefits is not usually conferred by mutual funds?", o:["Diversified investment portfolio", "Professional stock selection and asset management", "Tax benefits", "Assured returns"], a:3 },
{ c:6, q:"The mutual funds are likely to perform better in the market than a small investor because they", o:["Depend on the technical analysis tools and have the expertise to use them", "Depend on the fundamental analysis which ensures the long-term performance of the fund", "Have access to better information, ability and infrastructure to utilize it", "None of the above"], a:2 },
{ c:6, q:"Identify the statement that applies to open-end mutual funds", o:["They do not redeem or issue shares", "Shares of such funds are traded on organized exchanges", "Their price can't fall below the NAV", "Exit from such funds involves selling shares to other investors."], a:1 },
{ c:6, q:"How much money would you need to purchase 400 shares of a mutual fund with a NAV of Rs. 55 per share and a 3% load?", o:["Rs.22,000", "Rs.21,450", "Rs.23,200", "Rs.22.660"], a:3 },
{ c:6, q:"A mutual fund had average daily assets of Rs.500 million in the past year. During the year, the fund sold Rs.60 million of stock X and purchased Rs.90 million of stock Y. What was the fund's turnover ratio?", o:["12%", "15%", "18%", "30%"], a:0 },
{ c:6, q:"If opening units 10,000 Units subscribe 3000, Units redeem 1000 then Closing units?", o:["10,000 units", "13,000 units", "12,000 units", "14,000 units"], a:2 },
{ c:6, q:"For a scheme to be defined as an equal fund, it must have a minimum", o:["65% in Indian equities", "65% in equities", "51% Indian equities", "35% in Indian equities"], a:1 },
{ c:6, q:"If opening units 1,25,000 Units subscribe 2,00,000, Units redeem 50,000 then Closing units?", o:["3,25,000 units", "2,75,000 units", "3,75,000 units", "2,50,000 units"], a:1 },
{ c:6, q:"For a scheme to be defined as an equal fund, it must have a minimum", o:["65% in Indian equities", "65% in equities", "51% Indian equities", "35% in Indian equities"], a:1 },
{ c:7, q:"A portfolio having two risky securities can be turned risk less if", o:["The securities are completely positively correlated", "If the correlation ranges between zero and one", "The securities are completely negatively correlated", "None of the above"], a:2 },
{ c:7, q:"Total risk includes", o:["Systematic risk only", "Unsystematic risk only", "Both a and b above", "Only diversifiable risks"], a:2 },
{ c:7, q:"Risk of two securities with different expected return can be compared with", o:["Coefficient of variation", "Standard deviation of securities", "Variance of securities", "None of the above"], a:0 },
{ c:7, q:"A portfolio comprises two securities and the expected return on them is 12% and 16% respectively. Determine return of portfolio if first security constitutes 40% of total portfolio.", o:["12.40%", "13.40%", "14.40%", "15.40%"], a:2 },
{ c:7, q:"Mr. A invested Rs. 10,000 in a shares of XYZ Company 10 years ago, and that is shares (including reinvested dividends) are currently worth Rs.23,8000. Using this information, calculate total investment return of Mr. A", o:["100%", "38%", "138%", "238%"], a:2 },
{ c:7, q:"What is the annualized return of Mr. A based on the data of the above question?", o:["8%", "9.06%", "10%", "11%"], a:1 },
{ c:7, q:"Mr. X invested Rs. 10,000 in shares of XYZ Company 20 years ago, and that his shares (including reinvested dividends) are currently worth Rs. 18,800. Using this information, calculate total investment return of Mr. A.", o:["100%", "38%", "58%", "88%"], a:3 },
{ c:8, q:"Covariance between a stock and a market index and the variance of the market index were found to be 33.56 and 19.15 respectively. The beta of the stock is:", o:["1.55", "1.75", "1.85", "2.05"], a:1 },
{ c:8, q:"Consider the information given below: Rate of inflation = 5.1%, Beta = 0.85, Real rate of return = 4.2% and Market return = 12.6%. The risk premium for the above security will be-", o:["2.50%", "2.65%", "2.805%", "2.95%"], a:2 },
{ c:8, q:"The security market line's first point is riskless asset with a beta of zero and the second point on the line is beta of", o:["1", "1.5", "2.0", "0.5"], a:0 },
{ c:8, q:"Arbitrage portfolio", o:["Offers profit potential with an amount of additional investment and risk.", "Offers profit potential without an amount of additional investment and risk.", "Is the most diversified portfolio.", "Is the most undiversified portfolio."], a:1 },
{ c:8, q:"In contrast to the CAPM, arbitrage pricing theory:", o:["Requires that markets be in equilibrium", "Uses risk premiums based on micro variables", "Specifies the number and identifies specific factors that determine expected returns.", "Does not require the restrictive assumptions concerning the market portfolio."], a:3 },
{ c:8, q:"The feature of the general version of the arbitrage pricing theory (APT) that offers the greatest potential advantage over the simple CAPM is the:", o:["Identification of anticipated changes in production, inflation, and term structure of interest rates as key factors explaining the risk return relationship.", "Superior measurement of the risk free rate of return over historical time periods.", "Variability of coefficients of sensitivity to the APT factors for a given asset over time.", "Use of several factors instead of a single market-index to explain the risk-return relationship."], a:3 },
{ c:8, q:"Which of the following is a valid comparison between the APT and CAPM?", o:["The CAPM applies to only welldiversified - portfolios.", "The CAPM dominates the APT and econometric concerns appear to favor it", "The APT gets us to the expected return-beta relationship without requiring many of the unrealistic assumptions of the CAPM.", "Both theories differ on the expected return-beta relationship."], a:2 },
{ c:7, q:"The sum of an asset's systematic variance and its non-systematic variance of returns is equal to the asset's:", o:["Beta.", "Total risk.", "Total variance.", "None"], a:2 },
{ c:9, q:"The portfolio's risk premium is 12% and the standard deviation of market and the portfolio are 4 and 3, respectively. The fund's beta value is 1.5. The Treynor index is", o:["3.0", "8.0", "4.0", "12"], a:1 },
{ c:9, q:"A portfolio manager realized an average annual return of 12%. The beta of the portfolio is 1.1 and the standard deviation of returns is 30%. The average annual return for the market index is 10% and the standard deviation of the market returns is 25%. The rf is 5%. Calculate Jensen's alpha for the portfolio.", o:["0.50%", "0.5%", "1.50%", "1.5%"], a:1 },
{ c:9, q:"A portfolio manager realized an average annual return of 15%. The beta of the portfolio is 1.2 and the standard deviation of return is 25%. The average annual return for the market index was 11% and the standard deviation of the market returns is 20%. The risk-free rate is 4%. Calculate the Sharpe ratio for the portfolio.", o:["0.16", "0.44", "0.55", "0.64"], a:1 },
{ c:9, q:"Sharpe's measure of the portfolio performance is based on", o:["Systematic risk of the portfolio", "Unsystematic risk of the portfolio", "Total risk of the portfolio", "Market risk of the portfolio"], a:2 },
{ c:9, q:"Which of the following is the more appropriate measure of portfolio performance if you have only one mutual fund in your investment portfolio?", o:["Jensen measure", "Sharpe measure", "Treynor measure", "Information ratio"], a:1 },
{ c:9, q:"Sharpe measure is best applicable when", o:["Evaluating a portfolio to be mixed with a position in the passive benchmark portfolio", "Choosing among portfolios competing as the optional risky position", "Comparing with the desired performance based on a benchmark portfolio with actual performance", "Ranking many portfolios that will be mixed to form the optional risky portfolio"], a:1 },
{ c:10, q:"Which of the following statement defines an efficient market?", o:["Information is fully reflected in the stock prices", "The company's financial performance", "The stock exchange is fully automated", "Free entry and exit of investors"], a:0 },
{ c:10, q:"In a weakly efficient market, the stock price reflects", o:["The stock exchange is fully automated", "The past price of the scrip", "The demand for the scrip", "The past price and traded volume"], a:3 },
{ c:10, q:"In the strong form of efficient market", o:["All available information is reflected in prices", "All published information is reflected in prices", "Stock price reflects past price", "All information including insider information is reflected in prices"], a:3 },
{ c:10, q:"If markets are efficient, the security price provides", o:["Inadequate return for taking up risk", "Normal return for the level of risk taken", "High return for the level of risk taken", "Both 2 and 3"], a:1 },
{ c:10, q:"A run in the stock price is", o:["A sequence of either a fall or rise in stock prices", "An uninterrupted sequence of either a rise or fall in stock prices", "An alternate sequence of stock price and volume movements", "A sequence of fall in price"], a:1 },
{ c:10, q:"The efficient market hypothesis suggests that investors should", o:["Adopt an active portfolio management strategy", "Adopt a passive portfolio management strategy", "Use technical analysis as the basis for investment decisions", "Use fundamental analysis as the basis for investment decisions"], a:1 },
{ c:11, q:"Risk management is the process which includes", o:["Risk identification", "Risk assessment", "Risk measurement", "All of the above"], a:3 },
{ c:11, q:"Which of the following is not a part of Financial Risk?", o:["Operational Risk", "Market Risk", "Credit Risk", "Liquidity Risk"], a:0 },
{ c:11, q:"Which of the following is not a part of Market Risk?", o:["Equity risk", "Inflation Risk", "Downgrade Risk", "Interest Rate Risk"], a:2 },
{ c:11, q:"Which of the following is not a part of Credit Risk?", o:["Default risk", "Downgrade risk", "Concentration risk", "Liquidity risk"], a:3 },
{ c:11, q:"Responses to risk includes", o:["Risk avoidance", "Risk reduction", "Risk transfer", "All of the above"], a:3 },
{ c:11, q:"There are ______ -primary types of credit risk:", o:["2", "3", "4", "5"], a:1 },
{ c:11, q:"______ is the risk of uncertain movements and adverse fluctuations in the financial market variables like security prices, commodity prices, interest rates and exchange rates.", o:["Market risk or price risk", "Credit Risk", "Liquidity Risk", "None of these"], a:0 },
{ c:11, q:"Responses to risk generally fall into which of the following categories?", o:["Risk avoidance, Risk reduction, Risk escaping and Risk acceptance", "Risk avoidance, Risk reduction, Risk sharing or transfer and Risk acceptance", "Risk avoidance, Risk reduction, Risk intolerance and Risk acceptance", "Risk avoidance, Risk reduction, Risk creation and Risk acceptance"], a:1 },
{ c:11, q:"______ is the risk of change in the inflation rates changes the purchasing power.", o:["Inflation Rate Risk", "Currency Risk", "Commodities Risk", "None of these"], a:0 },
{ c:11, q:"Downgrade Risk", o:["Is the chance that the spread between the risky bond and risk-free securities will vary after purchase.", "Is a chance that a rating agency will lower its rating on the issuer or the probability of loss from a fall in issuers rating because of deterioration in its financial condition.", "The risk of loss arising from sovereign state freezing foreign currency payments (transfer/ conversion risk) or when it defaults on its obligations.", "Is the chance of failing of an issuer to meet its obligations."], a:1 },
{ c:12, q:"An investor writes a three-month put on the stock of an oil company at an exercise price of Rs.275 per share at a premium of Rs.34. If the expiration date price is Rs.280, calculate the gain/loss of put writer.", o:["Rs. 5", "-Rs.5", "Rs. 34", "None of these"], a:2 },
{ c:12, q:"An investor buys 100 shares of a sugar mill at Rs.210 per share and at the same time writes a September Rs.250 call at a premium of Rs.20 per share. If the expiration date price is Rs.280, calculate the net gain/loss.", o:["Rs.20", "Rs.40", "Rs.60", "None of these"], a:2 },
{ c:12, q:"If the share of BA Ltd. (F. V. Rs. 10) quotes Rs.920 on NSE, and the 3 months futures price quotes at Rs.950, and the borrowing rate is given as 8% and the expected annual dividend yield is 15% p.a. payable before expiry, then the price of 3-month BA Ltd. futures would be", o:["Rs.948.40", "Rs.939.90", "Rs. 938.50", "Rs.936.90"], a:3 },
{ c:12, q:"The stock of ABC Ltd. sells for Rs.240. The present value of exercise price and the value of call option are Rs.217.40 and Rs.9.60 respectively. What is the value of put option?", o:["Rs.16.50", "Rs.22.00", "Rs.17.00", "Rs.18.00"], a:2 },
{ c:12, q:"In June 2022, a six month Call on Ritz Ltd.'s stock with an exercise price of Rs.25 sold for Rs.5. The stock price was Rs.20. The risk- free interest rate was 5% per annum. How much would you be willing to pay for a Put Option on Ritz Ltd.'s stock with same maturity and exercise price? [Given: PVIF (5%, 1/2 year) = 0.9756]", o:["Rs. 6.39", "Rs.9.39", "Rs. 2.39", "None of these"], a:1 },
{ c:12, q:"A buyer of forward contract will make profit if", o:["Future price is lower than the forward price", "Future price is higher than the forward price", "Future price is equal to the forward price", "Both 1 and 3"], a:1 },
{ c:12, q:"Which of the following is/are underlying instrument(s) in a Forward Rate Agreement?", o:["Interest rate", "Exchange rate", "Inflation rate", "Both 1 and 3"], a:0 },
{ c:12, q:"The market in which the futures price is greater than the spot price is referred to as", o:["Basis", "Contango", "Backwardation", "Reverse Cash and carry arbitrage market"], a:1 },
{ c:12, q:"Buying and selling call or put option with the same strike price but different expiration dates is called", o:["Long hedge", "Short hedge", "Horizontal option spread", "None of the above."], a:2 },
{ c:12, q:"Maintenance margins deposited by an investor in a futures contract is", o:["Greater than or equal to the initial margin", "Less than or equal to the initial margin", "Greater than the initial margin", "Less than the initial margin"], a:3 },
{ c:12, q:"Backwardation occurs when", o:["Current spot price = futures price", "Current spot price < futures", "Futures price < current spot price", "Futures price > current spot price"], a:2 },
{ c:12, q:"American options are those", o:["Options which are traded on New York Stock Exchange", "That can be exercised at any time during a specified period", "That can be exercised only at the specified period", "That can be exercised even after the specified period"], a:1 },
{ c:12, q:"The writer of the option is also known as a", o:["Buyer of the option", "Holder of the option", "Seller of the option", "Mediator of the option"], a:2 },
{ c:12, q:"Covered Call Writing means", o:["Buying a stock and a put option and writing a call option on the asset already owned", "Buying a call option and stock and writing a put option", "Buying a call option and writing a put option", "Selling a call option and purchasing a stock"], a:3 },
{ c:12, q:"Plain vanilla interest rate swaps involved", o:["Fixed to fixed rate swap", "Fixed to floating rate swap", "Floating to floating rate swap", "Currency swap"], a:1 },
{ c:13, q:"Which of the following bonds are denominated in Yen?", o:["Yankee", "Samurai", "Shibosai", "Both 2 and 3"], a:3 },
{ c:13, q:"______ are underwritten and have a maturity of up to one year.", o:["Note issuance facilities", "Medium-term notes", "Commercial paper", "ADRS"], a:0 },
{ c:13, q:"______ is a private arrangement between lending banks and a borrower.", o:["Club loan", "Multiple component facility", "Syndicated Euro credit", "All of the above"], a:0 },
{ c:13, q:"A Yankee bond is", o:["A dollar dominated bond issued for global market by a non-US entity", "A dollar denominated bond issued in the US by a non-US entity", "A dollar denominated bond issued by a US resident to a non-US investor", "A dollar denominated bond issued in US by a US resident"], a:1 },
{ c:13, q:"Shibosai bond is a bond", o:["Denominated in ¥ and issued outside Japan", "Denominated in a currency other than and issued in Japan", "Denominated in Japanese ¥ and issued under private placement in Japan", "Denominated in ¥ and issued by a overseas corporate to the public in Japan"], a:2 },
{ c:13, q:"Which of the following is/are advantage/s of ADRS?", o:["Access to Large Capital", "Access to Foreign Exchange", "No Change in the Shareholding/voting pattern", "All of the above"], a:3 },
{ c:13, q:"Which of the following is/are feature/s of GDRs?", o:["Underlying Shares", "Globally Marketed", "Not negotiable", "Both 1 and 2"], a:3 },
{ c:14, q:"An Indian company is planning to invest in US. The US inflation rate is expected to be 3% and that of India is expected to be 8% annually. If the spot rate currently is Rs.45/US $, what spot rate can you expect after 5 years?", o:["Rs.56.09/US $", "Rs.57.00/US $", "Rs.57.04/US $", "Rs.57.13/USS"], a:2 },
{ c:14, q:"The spot and 6 months forward rates of £ in relation to the rupee (Rs./£): are Rs.77.9542/78.1255 and Rs.78.8550/9650 respectively. What will be the annualised forward margin (Premium with respect to Ask Price)?", o:["2.31%", "2.15%", "1.80%", "1.59%"], a:1 },
{ c:14, q:"The United States Dollar is selling in India at Rs.45.20. If the interest rate for a 6-months borrowing in India is 10% and the corresponding rate in USA is 4%, what would be the rate of forward premium/(discount)?", o:["5.93%", "5.88%", "(5.17%)", "(5.52%)"], a:1 },
{ c:14, q:"The sterling is trading at $1.6400 today. Inflation U.K. is 3.8% and that in U.S.A. is 2.9%. What would be the spot rate ($/£) after 2 years?", o:["$1.6117", "$1.615", "$1.625", "None of the above"], a:0 },
{ c:16, q:"Components of digital infrastructure includes which of the following?", o:["Data centers and networks", "Enterprise portals, platforms, systems, and software", "Cloud services", "All of these"], a:3 },
{ c:16, q:"Which of the following is not a potential benefit of Central Bank Digital Currencies?", o:["Technological efficiency in storing and transacting with reduced cost", "Scope committing illegal activities like money laundering, tax evasion, terror financing", "Keeping track of transactions, exact location of money", "Providing a digital record of every transaction"], a:1 },
{ c:16, q:"______ is unique. Non-fungible tokens can digitally represent any asset, including online-only assets like digital artwork and real assets such as real estate.", o:["Non-Fungible Tokens", "Cryptocurrency", "Central Bank Digital Currencies", "None of these"], a:0 },
{ c:16, q:"Which of the following is not a component of Digital Finance Ecosystem?", o:["Digital Infrastructure", "Digital Money", "Digital Liabilities", "Digital Financial Services"], a:2 },
{ c:16, q:"NFT stands for", o:["Non-Fungible Token", "Non-Fuel Token", "Non-Fractional Token", "Non-Fundamental Token"], a:0 },
{ c:16, q:"Digital Finance Cube has ______ dimensions.", o:["6", "4", "3", "2"], a:2 },
{ c:16, q:"In India, all payments are regulated by", o:["RBI Act, 1934", "Banking Regulation Act, 1949", "Payment and Settlement Systems Act, 2007", "SBI Act, 1955"], a:2 },
{ c:16, q:"UPI stands for", o:["United Payment Interface", "Unified Payment Interface", "Unique Payment Interface", "Utility Payment Interface"], a:1 },
{ c:12, q:"The price of Reliance stock on 31st December 2024 was Rs.220, and the futures price for March 2025 on the same date was 230. Other relevant details are as follows: Time to expiration: 3 months (0.25 year) Borrowing rate: 15% p.a. Annual dividend on the stock: 25% of face value, payable before 31st March 2025 Face value of the stock: Rs. 10. Calculate the futures price of Reliance stock on 31st December 2024.", o:["Rs.220.09", "Rs.217.59", "Rs.225.75", "Rs.227.75"], a:2 },
{ c:12, q:"The 6-months forward price of a security is Rs.220.41. The borrowing rate is 5% per annum payable with monthly rests. What should be the spot price?", o:["Rs.212", "Rs.215", "Rs.217", "Rs.210"], a:3 },
{ c:12, q:"The current price of OLA stock (Face Value Rs. 10) on NSE is Rs. 125. A 3-month futures contract on OLA is quoted at Rs. 135. The expected annual dividend on the stock is 28% of the face value, payable before the contract expiry. The borrowing rate is 10% per annum.", o:["Rs.125.33", "Rs.124.5", "Rs.127", "Rs.126"], a:0 },
{ c:12, q:"The current market price of a share of NLC Ltd is Rs.330. Over the next 3 months, the share price is expected to fluctuate between a maximum of Rs.400 and a minimum of Rs.300. The risk-free interest rate is 8% per annum. Using the risk-neutral method, calculate the value of a 3-month call option with a strike price of Rs.350. Given: e0.02 = 1.0202", o:["Rs.16.5", "Rs.17", "Rs.17.95", "Rs.18.5"], a:2 },
{ c:12, q:"A trader sells a call option. What is the maximum possible profit he can earn?", o:["Unlimited", "Limited to the premium received", "Strike price minus the premium received", "No profit possible, since the loss potential is unlimited"], a:1 },
{ c:12, q:"A company wants to hedge its equity portfolio worth Rs.225 million using index futures. The contract size is 100 times the index, and the index is currently quoted at 6500. The portfolio has a beta of 0.5, while the beta of the index is considered as 1. How many index futures contracts should be traded to achieve the hedge?", o:["225", "346", "173", "450"], a:2 },
{ c:12, q:"A company's share is currently trading at Rs.440. After 6 months, the share price will either increase to Rs.450 with probability 0.70 or decrease to Rs.420 with probability 0.30. A European call option exists with an exercise price of Rs.430. What will be the expected value of the call option at maturity?", o:["Rs.10", "Rs.14", "Rs.16", "Rs.12"], a:1 },
{ c:12, q:"You are given the following information about a stock: Strike Price: Rs.200 Current Stock Price: Rs.172 Risk-free Interest Rate (r): 5% p.a. Time to Maturity: 6 months (0.5 years). What is the theoretical minimum price of a European put option?", o:["Rs.27.5", "Rs.29.2", "Rs.23.1", "Rs.28.05"], a:2 },
{ c:12, q:"A stock is currently trading at Rs. 150. A European put option with a strike price of Rs. 190 is selling in the market at a premium of Rs.30. What will be the time value of this put option?", o:["Rs.0", "Rs.10", "Rs.5", "Rs.15"], a:1 },
{ c:12, q:"Sandhya is bearish about the market index. The Spot Nifty is currently at Rs. 1,420. She decides to buy five three-month Nifty put option contracts, each with a market lot of 200 units, at a strike price of Rs.1,530 for a premium of Rs.40 per unit. At the end of three months, the Nifty closes at Rs.1,480. What will be Sandhy's net payoff on this position?", o:["Rs.10000", "Rs.8000", "Rs.12000", "Rs.1480"], a:0 },
{ c:12, q:"Imran is bearish on the market and sells one January Nifty futures contract on January 15 for Rs.5,25,000. For this, he deposits an initial margin of Rs.36,250 with his broker. Each Nifty futures contract represents 200 Nifties. On January 25, the Nifty index closes at Rs.2,750. What is Imran's profit/loss on this position?", o:["Profit of Rs.20,000", "Loss of Rs.25,000", "Profit of Rs.25,000", "Loss of Rs.20,000"], a:1 },
{ c:12, q:"In the futures market, when are call options and put options said to be out of the money'?", o:["Call options and put options are never out of the money; they are only in the money or at the money.", "A call option is out of the money when the spot price > strike price, and a put option is out of the money when the spot price < strike price.", "Both call and put options are out of the money when the spot price = strike price.", "A call option is out of the money when the spot price < strike price, and a put option is out of the money when the spot price > strike price."], a:3 },
{ c:12, q:"CNX Nifty is currently trading at 4300. An investor purchases a May futures contract at 4500. Each lot consists of 25 units, and the initial margin requirement is 6%. What amount must the investor deposit as the initial margin? To what level must the Nifty futures rise to achieve a 5% gain on the initial margin?", o:["Initial Margin = Rs.6,750; Target Futures Price = 4513.5", "Initial Margin = Rs.7,500; Target Futures Price = 4525", "Initial Margin = Rs.6,500; Target Futures Price = 4510", "Initial Margin = Rs.6,750; Target Futures Price = 4520"], a:0 },
{ c:0, q:"A project requires an initial investment of Rs.40 lakhs. The expected annual cash inflows are Rs.8.5 lakhs for 10 years. The cost of capital is 12%, and the annuity factor for 12% for 10 years is 5.6502. What is the Profitability Index (PI) of the project?", o:["1.1", "1.3", "1.2", "1.25"], a:2 },
{ c:1, q:"The probability distribution of a project's NPV is given below: NPV (25,000) Prob 0.1, NPV (50,000) Prob 0.3, NPV (1,00,000) Prob 0.4, NPV (1,20,000) Prob 0.2. If the initial cost of the project is Rs.2,00,000, the Profitability Index (PI) of the project is:", o:["1.27", "1.41", "1.33", "1.5"], a:1 },
{ c:0, q:"A project has the following details: Annual cash inflow: Rs.50,000, Useful life: 4 years, Payback period: 2.305 years. Calculate the cost of the project.", o:["Rs.100000", "Rs.110000", "Rs.115250", "Rs.120500"], a:2 },
{ c:0, q:"A 5-year project has a Net Present Value (NPV) of Rs.550 lakh. The Present Value Interest Factor of Annuity (PVIFA) at 15% for 5 years is 3.352. Calculate the Equivalent Annual Benefit (EAB) of the project.", o:["Rs.150 lakh per year", "Rs.160 lakh per year", "Rs. 164 lakh per year", "Rs.170 lakh per year"], a:2 },
{ c:0, q:"The following information is available for an investment proposal: NPV at a discount rate of 8% = $1,550 lakh. NPV at a discount rate of 9% = (-) 300 lakh. The Internal Rate of Return (IRR) of the proposal is:", o:["8.84%", "8.50%", "9.00%", "9.20%"], a:0 },
{ c:1, q:"A project has an expected Net Present Value (NPV) of Rs.2,30,000 and a standard deviation of Rs.69,000. Calculate the Coefficient of Variation (CV) of the project.", o:["0.25", "0.3", "0.35", "0.4"], a:1 },
{ c:0, q:"A company wishes to earn a real rate of return of 18% from its project, while the inflation rate is 9%. The normal (nominal) rate of return the company should target is:", o:["25.20%", "27.00%", "28.60%", "30.00%"], a:2 },
{ c:0, q:"Depreciation is included as a cost in which of the following capital budgeting techniques?", o:["Payback Period Method", "Accounting Rate of Return (ARR) Method", "Net Present Value (NPV) Method", "Internal Rate of Return (IRR) Method"], a:1 },
{ c:0, q:"When two alternative proposals are such that the acceptance of one automatically excludes the possibility of accepting the other, the decision-making is referred to as:", o:["Mutually exclusive decisions", "Accept-Reject Decisions", "Contingent decisions", "None of the above"], a:0 },
{ c:6, q:"The following information is extracted from HDDD Mutual Fund Scheme: NAV on 01-11-2024 = Rs.88.25. Annualized return = 25%. Distributions of income and capital gains during the month = Rs.0.40 and Rs.0.20 per unit respectively. What will be the NAV on 30-11-2024?", o:["Rs.88.95", "Rs.89.05", "Rs.89.49", "Rs.90"], a:2 },
{ c:9, q:"A certain mutual fund scheme has the following details: Portfolio return = 25%. Standard deviation = 4.2%. Sharpe Ratio = 5. What is the risk-free rate of return?", o:["3.00%", "3.50%", "4.00%", "4.50%"], a:2 },
{ c:9, q:"The following information is available for a mutual fund scheme: Portfolio Return (Rp) = 22%. Risk (Standard Deviation, σ) = 25%. Beta (β) = 0.80. Risk-free Rate (Rf) = 19%. What is the Treynor's Ratio of the mutual fund?", o:["0.025", "0.03", "0.0375", "0.04"], a:2 },
{ c:6, q:"A mutual fund had a Net Asset Value (NAV) of Rs.25 at the beginning of a month. During the month, it distributed an income of Rs.0.0456 per share and a capital gain of Rs.0.04 per share. At the end of the month, the NAV was Rs.25.05. What is the monthly return of the fund?", o:["10.42%", "0.54%", "0.64%", "0.75%"], a:1 },
{ c:6, q:"TVD Plan, a hedge fund, currently has assets of Rs.20 crore. CMA Vivek, the manager of the fund, charges: A management fee of 0.10% of portfolio assets, and An incentive fee of 2%, linked to the gross return each year in excess of the portfolio's maximum value since inception. The maximum value the fund has achieved since inception was Rs.21 crore. If the fund earns a return of 8% during the year, compute the total fee payable to CMA Vivek.", o:["Rs.200000", "Rs.280000", "Rs.320000", "Rs.360000"], a:2 },
{ c:6, q:"Mr. Umapada can earn a return of 25% by investing in equity shares on his own. He is now considering a recently announced equity-based mutual fund scheme in which: Initial expenses: 8.22%, Annual recurring expenses: 2.1%. How much must the mutual fund earn before expenses to provide Mr. Umapada with a net return of 25%?", o:["27.15%", "29.53%", "30.10%", "28.42%"], a:1 },
{ c:12, q:"Which of the following is not a derivative instrument?", o:["Futures", "Options", "Swaps", "Mutual funds"], a:3 },
{ c:12, q:"Which of the following is true about options?", o:["Buyer has right, seller has obligation", "Both buyer and seller have right", "Only buyer has right and obligation", "Both buyer and seller have obligation"], a:0 },
{ c:12, q:"The initial margin is required in:", o:["Forward contract", "Futures contract", "Option contract", "Swap contract"], a:1 },
{ c:12, q:"Hedging using derivatives aims to:", o:["Maximize speculative gain", "Eliminate risk", "Increase leverage", "Avoid taxes"], a:1 },
{ c:12, q:"A company enters into an interest rate swap with a notional principal of $2 million. Under the swap: The company pays a fixed rate of 7% per annum. The company receives a floating rate equal to LIBOR of 6% per annum. What is the net cash flow for the company for the year?", o:["$20,000", "$14,000", "$7,000", "$2,000"], a:0 },
{ c:7, q:"The probability distribution of security N is given below: Probability 0.167 for Return 60, Probability 0.333 for Return 30, Probability 0.500 for Return 20. The risk (standard deviation) of the return of the security is approximately:", o:["10", "12", "14", "16"], a:2 },
{ c:7, q:"An investor has the following two-security portfolio: Security A: Expected Return = 12%, Standard Deviation = 18%. Security B: Expected Return = 8%, Standard Deviation = 10%. The correlation coefficient between A and B is 0.30. The investor invests Rs.60,000 in Security A and Rs.40,000 in Security B. What will be the expected return and standard deviation (risk) of the portfolio?", o:["Expected Return = 10.4%, Portfolio Risk = 13.7%", "Expected Return = 11.2%, Portfolio Risk = 14.5%", "Expected Return = 11.0%, Portfolio Risk = 13.2%", "Expected Return = 10.4%, Portfolio Risk = 12.6%"], a:3 },
{ c:7, q:"An investor allocates 70% of wealth in Security A (Expected Return = 15%) and 30% in Security B (Expected Return = 9%). What is the expected portfolio return?", o:["13.20%", "14.20%", "12.60%", "11.20%"], a:0 },
{ c:7, q:"Security A: σ = 12%, Weight = 0.5. Security B: σ = 8%, Weight = 0.5. Correlation = 0. Portfolio Risk = ?", o:["10.8%", "7.2%", "6.3%", "9.8%"], a:1 },
{ c:7, q:"A (σ=20%, weight = 0.6), B (σ=10%, weight = 0.4), correlation = 0.5. Find portfolio σ.", o:["17.00%", "15.50%", "16.00%", "14.42%"], a:3 },
{ c:7, q:"A (ER=10%, w=0.4) B (ER=12%, w=0.6). Portfolio ER = ?", o:["11.20%", "12%", "11.60%", "10.80%"], a:0 },
{ c:9, q:"Portfolio return = 14%, risk-free = 6%, portfolio σ = 12%. Sharpe Ratio = ?", o:["0.67", "0.75", "0.5", "0.9"], a:0 },
{ c:8, q:"Rf = 5%, β = 1.2, Rm = 14%. Find expected return.", o:["15.80%", "16.80%", "14.50%", "13.80%"], a:0 },
{ c:7, q:"σA = 10%, σB = 20%, ρ = -1. Weight of A for zero-risk = ?", o:["0.33", "0.5", "0.67", "0.25"], a:2 },
{ c:9, q:"Portfolio return = 13%, risk-free = 6%, β = 1.1. Treynor Ratio = ?", o:["6.36%", "5.80%", "7.45%", "4.87%"], a:0 },
{ c:9, q:"Portfolio return = 15%, Rf = 5%, β = 1.2, Rm = 12%. Alpha = ?", o:["1.60%", "2.40%", "0%", "-1%"], a:0 },
{ c:7, q:"Which of the following can reduce unsystematic risk?", o:["Investing in more stocks", "Investing in only one industry", "Increasing leverage", "Investing in derivatives"], a:0 },
{ c:11, q:"Liquidity risk in a portfolio refers to:", o:["Price volatility", "Difficulty in quickly converting assets into cash", "Systematic market risk", "Credit risk of companies"], a:1 },
{ c:9, q:"Which of the following is considered a \"reward-to-volatility\" measure?", o:["Beta", "Alpha", "Sharpe Ratio", "Correlation coefficient"], a:2 },
{ c:2, q:"A company is considering leasing a machine costing Rs.20,00,000 for 3 years. The lease rentals are Rs.6,00,000 per year payable at the end of each year. If the cost of debt is 10%, what is the Present Value (PV) of lease payments?", o:["Rs.1492200", "Rs.1482200", "Rs.1200000", "Rs.1500000"], a:0 },
{ c:2, q:"A company has an option to lease equipment for Rs.4,00,000 per year for 4 years or purchase it for Rs. 12,00,000 financed by 12% debt repayable in 4 equal instalments. Assuming no taxes, which is cheaper?", o:["Lease", "Buy", "Both are equal", "Depends on salvage value"], a:1 },
{ c:2, q:"Asset cost = Rs. 12,00,000. Lease term = 5 years. Tax = 30%. Discount rate = 10%. What annual lease rental (before tax) makes the lessee indifferent?", o:["Rs.400000", "Rs.350000", "Rs.310000", "Rs.280000"], a:2 },
{ c:2, q:"Lease rental = Rs.7,00,000 per year for 4 years. Asset cost = Rs.24,00,000. Tax = 35%. Discount rate = 12%. Should the company lease?", o:["Yes", "No", "Indifferent", "None of the above"], a:0 },
{ c:2, q:"A machine can be leased at Rs.4,00,000 p.a. for 3 years or Rs.3,00,000 p.a. for 5 years. Discount rate = 10%, tax ignored. Which lease term is cheaper in PV terms?", o:["3 years", "5 years", "Both", "None of the above"], a:0 },
{ c:5, q:"EPS Rs.30, P/E = 12. Find intrinsic price.", o:["Rs.250", "Rs.275", "Rs.300", "Rs.360"], a:3 },
{ c:5, q:"Face Value Rs.5,000, maturity 5 yrs, YTM = 9%. Price of the bond = ?", o:["Rs.3249", "Rs.4565", "Rs.3600", "Rs.4345"], a:0 },
{ c:8, q:"If a stock has expected return = 15%, β = 1.5, Rf = 5%, Market premium = 8%, is the stock overvalued or undervalued?", o:["Overvalued", "Undervalued", "Fairly valued", "None of the above"], a:0 },
{ c:8, q:"A stock has a beta (β) of 0.75. What does this indicate about the stock's volatility relative to the market?", o:["Less volatile than market", "More volatile than market", "No correlation with market", "Market neutral"], a:0 },
{ c:8, q:"Market risk premium = 10%, β = 1.8. What is stock's risk premium?", o:["10%", "18%", "5%", "9%"], a:1 },
{ c:9, q:"A stock has positive alpha. What does it indicate?", o:["Underpriced", "Overpriced", "Fairly priced", "Market neutral"], a:0 },
{ c:14, q:"The spot and 6-month forward rates of the US dollar against the Indian Rupee are as follows: Spot Rate (Rs./$): Rs.84.532/Rs.85.4143. 6-Month Forward Rate (Rs./$): Rs.85.1278/Rs.86.2538. Calculate the annualized forward margin with respect to the Ask price.", o:["1.75% p.a.", "1.97% p.a.", "2.23% p.a.", "2.50% p.a."], a:1 },
{ c:14, q:"RRR Ltd. is planning to invest in the USA. The annual inflation rates are 5% in India and 2% in the USA. If the current spot rate is Rs.85.5/$, what spot rate can the company expect after 3 years?", o:["Rs.93.3", "Rs.82.65", "Rs.95.2", "Rs.87.87"], a:0 },
{ c:14, q:"You are a forex dealer in India. The prevailing international market rates are: 1 Rs. = US $0.0117647 and 1 £ = US $1.341032. What will be your direct quote for £ (pound) in terms of Rs. (rupees) to your customer?", o:["Rs.108.25/£", "Rs.113.99/£", "Rs.118.50/£", "Rs.120.75/£"], a:1 },
{ c:14, q:"ABC Ltd., a valued customer engaged in import business, needs to remit EURO 1 million to its European exporter. The following spot rates are available: ₹/US$ = $85.47/85.57 and US$/€ = $0.8501/0.8505. If the bank charges a margin of 0.50%, what rate will the banker quote to ABC Ltd.?", o:["Rs.73.14/Euro", "Rs.75/Euro", "Rs.75.65/Euro", "Rs.77.34/Euro"], a:0 },
{ c:14, q:"An Indian company plans to make an investment in the United States. The expected annual inflation rates are 6% in India and 2% in the USA. If the current spot rate is Rs.85.2 per US dollar, what is the expected spot rate after 5 years, assuming the inflation rates remain constant over this period?", o:["Rs.103.26", "Rs.101.5", "Rs.105", "Rs.99.99"], a:0 },
{ c:14, q:"In the foreign exchange market, if the spot rate of USD/INR is Rs.85.20 and the 3-month forward rate is quoted at Rs.85.80, what does this indicate?", o:["The Rupee is at a forward premium against the Dollar", "The Dollar is at a forward premium against the Rupee", "The Rupee is appreciating in the forward market", "There is no difference between spot and forward rate"], a:1 },
{ c:14, q:"In the foreign exchange market, the direct quote method expresses", o:["Foreign currency in terms of domestic currency", "Domestic currency in terms of foreign currency", "Exchange rate including interest rate parity", "Only forward exchange rate"], a:0 },
{ c:15, q:"If the USD appreciates against the INR, what will be the impact on Indian importers?", o:["They will have to pay more in INR for the same USD payment", "They will have to pay less in INR for the same USD payment", "There will be no impact", "They will gain from the currency appreciation."], a:0 },
{ c:14, q:"Cross rate refers to:", o:["An exchange rate derived from two other currency pairs", "An exchange rate quoted directly by the central bank", "A spot rate adjusted for interest parity", "A forward rate adjusted for inflation"], a:0 },
{ c:15, q:"A currency option gives the holder the right to:", o:["Fix interest rates for deposits.", "Participate in inter-bank lending.", "An obligation to buy currency in the forward market", "Buy or sell foreign currency at a predetermined rate"], a:3 },
{ c:11, q:"Which of the following is an example of operational risk?", o:["Fluctuations in crude oil prices", "Increase in interest rates", "Human errors in processing transactions", "Currency depreciation"], a:2 },
{ c:11, q:"Which type of risk cannot be eliminated through diversification?", o:["Unsystematic risk", "Business risk", "Systematic risk", "Credit risk"], a:2 },
{ c:15, q:"Which of the following best defines currency risk?", o:["Risk of inflation increasing the cost of production", "Risk of loss due to adverse movement in exchange rates", "Risk of a borrower defaulting", "Risk of policy changes by the government"], a:1 },
{ c:16, q:"Which type of digital currency is issued and regulated by a central bank?", o:["Bitcoin", "Stablecoin", "Central Bank Digital Currency", "Tokenized Gold"], a:2 },
{ c:16, q:"Which technology allows digital finance companies to predict customer behavior and creditworthiness?", o:["Machine Learning and AI", "Physical audits", "Manual bookkeeping", "Blockchain mining"], a:0 },
{ c:16, q:"Stablecoins are designed to:", o:["Fluctuate rapidly in value", "Replace physical banknotes", "Be immune to regulation", "Maintain a fixed value relative to a fiat currency"], a:3 },
{ c:6, q:"The Net Asset Value (NAV) of a mutual fund represents:", o:["Total profit of the fund", "Market value of fund assets minus liabilities per unit", "Total number of units issued", "Manager's commission"], a:1 },
{ c:6, q:"Which type of mutual fund invests primarily in debt instruments?", o:["Equity fund", "Debt fund", "Balanced fund", "Money market fund"], a:1 },
{ c:6, q:"Load in mutual funds refers to:", o:["The fund manager's salary", "Entry or exit fees charged by the fund", "Total assets under management", "Government tax on dividends"], a:1 },
{ c:6, q:"Which of the following is an example of a hybrid mutual fund strategy?", o:["60% equity, 40% debt allocation", "100% cash allocation", "Only corporate bonds", "Only sector-specific stocks"], a:0 },
{ c:6, q:"Systematic Withdrawal Plan (SWP) allows investors to:", o:["Withdraw a fixed amount periodically from their mutual fund investment", "Invest in new units automatically", "Avoid all taxes", "Only withdraw principal"], a:0 },
{ c:6, q:"The beta of a mutual fund indicates:", o:["Volatility of the fund relative to the market", "Fund manager's experience", "Total NAV", "Dividend yield"], a:0 },
{ c:0, q:"The primary objective of capital budgeting is to", o:["Maximize shareholders' wealth","Increase sales","Reduce operating cost","Increase inventory"], a:0 },
{ c:0, q:"Which method considers the time value of money?", o:["Payback Period","Accounting Rate of Return","Net Present Value","Average Profit"], a:2 },
{ c:0, q:"If PI is greater than 1, the project should be", o:["Rejected","Accepted","Deferred","Ignored"], a:1 },
{ c:0, q:"Discounted Payback Period is always", o:["Less than Payback Period","Equal to Payback Period","Greater than Payback Period","Zero"], a:2 },
{ c:0, q:"Capital rationing generally occurs due to", o:["Unlimited funds","Limited investment funds","High sales","Low depreciation"], a:1 },
{ c:0, q:"The discounting rate used in NPV generally represents", o:["Inflation rate","Cost of capital","Tax rate","Dividend rate"], a:1 },
{ c:0, q:"Which technique directly measures increase in shareholders' wealth?", o:["ARR","Payback","NPV","Accounting Profit"], a:2 },
{ c:0, q:"IRR is the rate at which", o:["Profit is maximum","NPV becomes zero","Sales are highest","Cash inflow equals profit"], a:1 },
{ c:0, q:"A project with positive NPV should normally be", o:["Rejected","Accepted","Reconsidered","Delayed"], a:1 },
{ c:0, q:"Which method ignores cash flows after payback?", o:["NPV","IRR","Payback Period","PI"], a:2 },
{ c:0, q:"Salvage value is generally considered while calculating", o:["Terminal Cash Flow","Opening Investment","Working Capital","Dividend"], a:0 },
{ c:0, q:"Working capital recovered at the end of project is treated as", o:["Cash Outflow","Cash Inflow","Operating Cost","Sunk Cost"], a:1 },
{ c:0, q:"Depreciation is added back while computing cash flow because it is", o:["Revenue","Non-cash expense","Current asset","Liability"], a:1 },
{ c:0, q:"Which cost is ignored in capital budgeting?", o:["Relevant Cost","Opportunity Cost","Sunk Cost","Incremental Cost"], a:2 },
{ c:0, q:"Replacement decision mainly compares", o:["Old asset with new asset","Debt with Equity","Sales with Profit","Fixed cost with Variable cost"], a:0 },
{ c:1, q:"Sensitivity analysis studies the effect of change in", o:["One variable at a time","All variables together","Only sales","Only tax"], a:0 },
{ c:1, q:"Scenario analysis considers", o:["Single variable","Multiple variables simultaneously","Only inflation","Only cost"], a:1 },
{ c:1, q:"Decision tree is useful when", o:["Sequential decisions exist","No uncertainty exists","Only accounting data is available","Tax planning"], a:0 },
{ c:1, q:"Standard deviation measures", o:["Expected return","Risk","Liquidity","Profitability"], a:1 },
{ c:1, q:"Higher coefficient of variation indicates", o:["Lower risk","Higher risk","No risk","Constant return"], a:1 },
{ c:1, q:"Expected Monetary Value is calculated using", o:["Probability","Interest Rate","Tax Rate","Dividend"], a:0 },
{ c:1, q:"Simulation is also known as", o:["Monte Carlo Technique","Payback Method","IRR Method","Replacement Analysis"], a:0 },
{ c:1, q:"Risk adjusted discount rate generally", o:["Increases with risk","Decreases with risk","Remains constant","Becomes zero"], a:0 },
{ c:1, q:"Certainty equivalent approach adjusts", o:["Cash flows","Discount rate","Depreciation","Tax"], a:0 },
{ c:1, q:"Probability values always lie between", o:["0 and 1","1 and 2","-1 and 1","0 and 100"], a:0 },
{ c:2, q:"Operating lease is generally", o:["Short-term","Long-term","Perpetual","Compulsory"], a:0 },
{ c:2, q:"Finance lease generally covers", o:["Major part of asset life","Only one month","Only maintenance period","None"], a:0 },
{ c:2, q:"Ownership in operating lease remains with", o:["Lessee","Lessor","Government","Bank"], a:1 },
{ c:2, q:"Lease rentals are generally treated as", o:["Capital Receipt","Revenue Expense","Share Capital","Dividend"], a:1 },
{ c:2, q:"Lease financing helps in", o:["Preserving working capital","Increasing tax","Reducing production","Increasing liabilities only"], a:0 },
{ c:2, q:"Sale and Lease Back involves", o:["Selling asset and leasing it back","Buying asset twice","Selling inventory","Borrowing funds"], a:0 },
{ c:2, q:"Cross-border leasing involves", o:["Different countries","Same city","Same company","Government only"], a:0 },
{ c:2, q:"Lease or Buy decision is based mainly on", o:["NPV Comparison","Trial Balance","Sales","Production"], a:0 },
{ c:2, q:"Maintenance responsibility in finance lease is generally of", o:["Lessee","Lessor","Government","Bank"], a:0 },
{ c:2, q:"Lease agreement is between", o:["Lessor and Lessee","Shareholder and Company","Bank and Customer","Debtor and Creditor"], a:0 },
{ c:3, q:"Assets pooled for securitization are generally", o:["Income generating","Idle assets","Fixed deposits","Inventory"], a:0 },
{ c:3, q:"SPV stands for", o:["Special Purpose Vehicle","Special Payment Value","Security Protection Vehicle","Standard Portfolio Value"], a:0 },
{ c:3, q:"Securitization improves", o:["Liquidity","Pollution","Inflation","Tax"], a:0 },
{ c:3, q:"Originator transfers assets to", o:["SPV","Investor","Government","Bank"], a:0 },
{ c:3, q:"Investors receive returns from", o:["Cash flows of underlying assets","Government grants","Sales tax","Dividend only"], a:0 },
{ c:3, q:"Mortgage backed securities are examples of", o:["Securitized products","Equity shares","Preference shares","Debentures"], a:0 },
{ c:3, q:"Credit enhancement improves", o:["Credit rating","Inflation","Sales","Depreciation"], a:0 },
{ c:3, q:"Securitization mainly converts", o:["Illiquid assets into marketable securities","Cash into inventory","Equity into debt","Debt into equity"], a:0 },
{ c:3, q:"Pass Through Certificates are issued by", o:["SPV","Government","Depositor","Borrower"], a:0 },
{ c:3, q:"One advantage of securitization is", o:["Better liquidity","Higher pollution","Lower production","Inventory increase"], a:0 },
{ c:4, q:"Fundamental analysis primarily focuses on", o:["Intrinsic value of securities","Daily price fluctuations","Market rumours","Trading volume only"], a:0 },
{ c:4, q:"Technical analysis is mainly based on", o:["Price and volume movements","Financial statements","GDP only","Tax rates"], a:0 },
{ c:4, q:"Top-down approach begins with", o:["Economic Analysis","Company Analysis","Ratio Analysis","Dividend Analysis"], a:0 },
{ c:4, q:"Industry analysis is performed after", o:["Economic analysis","Company analysis","Ratio analysis","Trend analysis"], a:0 },
{ c:4, q:"Business cycle analysis is a part of", o:["Economic Analysis","Company Analysis","Technical Analysis","SWOT"], a:0 },
{ c:4, q:"Support level indicates", o:["Buying interest","Selling pressure","Inflation","Dividend"], a:0 },
{ c:4, q:"Resistance level indicates", o:["Selling pressure","Buying interest","Tax","Cash flow"], a:0 },
{ c:4, q:"Dow Theory is related to", o:["Technical Analysis","Cost Accounting","Budgeting","Taxation"], a:0 },
{ c:4, q:"Bull market is characterized by", o:["Rising prices","Falling prices","Stable prices","Zero returns"], a:0 },
{ c:4, q:"Bear market is characterized by", o:["Falling prices","Rising prices","High dividends","Stable inflation"], a:0 },
{ c:4, q:"SWOT stands for", o:["Strengths Weaknesses Opportunities Threats","Sales Wealth Operations Tax","Security Worth Output Trend","None"], a:0 },
{ c:4, q:"GDP growth generally indicates", o:["Economic expansion","Economic recession","Inflation only","Deflation"], a:0 },
{ c:4, q:"Inflation generally reduces", o:["Purchasing power","Tax","Production","Sales"], a:0 },
{ c:4, q:"Leading indicators predict", o:["Future economic activity","Past activity","Current assets","Sales only"], a:0 },
{ c:4, q:"Lagging indicators reflect", o:["Past performance","Future demand","Current tax","Future dividends"], a:0 },
{ c:5, q:"Dividend Discount Model values", o:["Equity shares","Debentures","Preference shares only","Bonds only"], a:0 },
{ c:5, q:"Bond value is equal to", o:["PV of interest + PV of principal","Face value only","Coupon only","Market value only"], a:0 },
{ c:5, q:"Current yield equals", o:["Annual Coupon / Market Price","Coupon / Face Value","Market Price / Coupon","Dividend / EPS"], a:0 },
{ c:5, q:"YTM means", o:["Yield to Maturity","Yearly Tax Method","Yield Transfer Model","None"], a:0 },
{ c:5, q:"A zero coupon bond pays", o:["No periodic interest","Monthly interest","Quarterly dividend","Half yearly bonus"], a:0 },
{ c:5, q:"If market interest rates rise, bond prices generally", o:["Fall","Rise","Remain constant","Become zero"], a:0 },
{ c:5, q:"P/E ratio compares", o:["Price with EPS","Price with Dividend","Book Value with Sales","Assets with Liabilities"], a:0 },
{ c:5, q:"Book value per share equals", o:["Net Worth / Number of Equity Shares","PAT / Shares","Sales / Shares","Assets / Liabilities"], a:0 },
{ c:5, q:"Dividend Yield equals", o:["Dividend per Share / Market Price","EPS / Price","PAT / Dividend","Book Value / Price"], a:0 },
{ c:5, q:"Intrinsic value greater than market price indicates", o:["Undervalued share","Overvalued share","Fair value","Worthless share"], a:0 },
{ c:5, q:"Face value of a bond is also called", o:["Par Value","Book Value","Market Value","Redemption Value"], a:0 },
{ c:5, q:"Callable bond can be redeemed by", o:["Issuer","Investor","Broker","Government"], a:0 },
{ c:5, q:"Puttable bond gives right to", o:["Investor","Issuer","Bank","SEBI"], a:0 },
{ c:5, q:"Coupon rate is based on", o:["Face value","Market value","Book value","NAV"], a:0 },
{ c:5, q:"Required rate of return is also known as", o:["Discount rate","Tax rate","Inflation rate","Dividend rate"], a:0 },
{ c:6, q:"NAV stands for", o:["Net Asset Value","Net Annual Value","New Asset Value","Net Average Value"], a:0 },
{ c:6, q:"Open-ended funds allow", o:["Continuous purchase and redemption","Fixed maturity only","No redemption","Trading only on exchange"], a:0 },
{ c:6, q:"Closed-ended funds are generally traded on", o:["Stock Exchange","Bank","AMC only","RBI"], a:0 },
{ c:6, q:"Mutual funds are managed by", o:["Asset Management Company","RBI","SEBI","Government"], a:0 },
{ c:6, q:"SEBI regulates", o:["Mutual Funds","Income Tax","GST","Customs"], a:0 },
{ c:6, q:"Equity funds mainly invest in", o:["Shares","Gold","Real Estate","Debentures only"], a:0 },
{ c:6, q:"Debt funds mainly invest in", o:["Fixed income securities","Equity only","Gold","Land"], a:0 },
{ c:6, q:"Balanced funds invest in", o:["Equity and Debt","Only Equity","Only Debt","Only Gold"], a:0 },
{ c:6, q:"Expense ratio is charged by", o:["AMC","Investor","Government","Auditor"], a:0 },
{ c:6, q:"Higher NAV always means", o:["Nothing about performance","Better performance","Poor performance","Guaranteed returns"], a:0 },
{ c:6, q:"SIP stands for", o:["Systematic Investment Plan","Special Investment Plan","Savings Income Plan","Strategic Investment Process"], a:0 },
{ c:6, q:"Mutual fund units are allotted based on", o:["Applicable NAV","Face Value","Book Value","Market Capitalization"], a:0 },
{ c:6, q:"Trustees protect the interest of", o:["Investors","AMC","Government","Banks"], a:0 },
{ c:6, q:"Load charged at purchase is", o:["Entry Load","Exit Load","Switch Load","Tax Load"], a:0 },
{ c:6, q:"Exit load is charged when", o:["Units are redeemed","Units are purchased","NAV rises","Dividend is paid"], a:0 },
{ c:7, q:"Portfolio means", o:["Collection of investments","Single share","Bank account","Loan account"], a:0 },
{ c:7, q:"Diversification helps in reducing", o:["Unsystematic Risk","Systematic Risk","Interest Rate","Inflation"], a:0 },
{ c:7, q:"Market risk is also known as", o:["Systematic Risk","Business Risk","Diversifiable Risk","Financial Risk"], a:0 },
{ c:7, q:"Unsystematic risk can be reduced through", o:["Diversification","Inflation","Tax Planning","Borrowing"], a:0 },
{ c:7, q:"Expected portfolio return is calculated using", o:["Weighted average of individual returns","Simple average","Median","Mode"], a:0 },
{ c:7, q:"Portfolio variance depends upon", o:["Covariance","Dividend","EPS","Face Value"], a:0 },
{ c:7, q:"Perfect positive correlation coefficient is", o:["+1","0","-1","2"], a:0 },
{ c:7, q:"Perfect negative correlation coefficient is", o:["-1","+1","0","0.5"], a:0 },
{ c:7, q:"If correlation is -1, portfolio risk can become", o:["Zero","Maximum","Double","Constant"], a:0 },
{ c:7, q:"Efficient portfolio offers", o:["Maximum return for given risk","Minimum return","Highest tax","Highest dividend"], a:0 },
{ c:7, q:"Risk-return trade off means", o:["Higher risk expects higher return","Higher risk lower return","Risk has no relation","Return is fixed"], a:0 },
{ c:7, q:"Standard deviation measures", o:["Total Risk","Return","Dividend","Liquidity"], a:0 },
{ c:7, q:"Portfolio beta measures", o:["Systematic Risk","Business Risk","Financial Risk","Default Risk"], a:0 },
{ c:7, q:"Diversification is effective when securities are", o:["Low correlated","Perfectly positively correlated","Identical","Same industry only"], a:0 },
{ c:7, q:"Risk-free asset has beta of", o:["0","1","-1","2"], a:0 },
{ c:8, q:"CAPM was developed by", o:["Sharpe","Taylor","Marshall","Fisher"], a:0 },
{ c:8, q:"CAPM establishes relationship between", o:["Risk and Return","Sales and Profit","Assets and Liabilities","Cost and Revenue"], a:0 },
{ c:8, q:"Beta measures", o:["Systematic Risk","Unsystematic Risk","Liquidity","Inflation"], a:0 },
{ c:8, q:"Market portfolio beta is", o:["1","0","2","-1"], a:0 },
{ c:8, q:"Security Market Line represents", o:["Expected Return vs Beta","Risk vs Sales","Profit vs Cost","NAV vs EPS"], a:0 },
{ c:8, q:"According to CAPM required return equals", o:["Risk-free rate + Risk Premium","Dividend + EPS","Profit + Tax","Sales + Cost"], a:0 },
{ c:8, q:"Beta greater than 1 indicates", o:["More volatile than market","Less volatile","Risk free","No risk"], a:0 },
{ c:8, q:"Beta less than 1 indicates", o:["Less risky than market","More risky","Negative return","No return"], a:0 },
{ c:8, q:"Risk premium equals", o:["Market Return - Risk Free Rate","Dividend - EPS","Sales - Cost","Tax - Profit"], a:0 },
{ c:8, q:"CAPM assumes investors are", o:["Risk Averse","Risk Loving","Neutral","Government"], a:0 },
{ c:8, q:"Alpha measures", o:["Excess Return","Inflation","Tax","Liquidity"], a:0 },
{ c:8, q:"Positive Alpha means", o:["Outperformance","Underperformance","No Return","Negative Return"], a:0 },
{ c:8, q:"Negative Alpha indicates", o:["Poor performance","Excellent performance","Risk free","No investment"], a:0 },
{ c:8, q:"SML intercept represents", o:["Risk Free Rate","Market Return","Dividend Yield","EPS"], a:0 },
{ c:8, q:"Capital Market Line applies to", o:["Efficient Portfolios","Individual Securities","Only Bonds","Only Mutual Funds"], a:0 },
{ c:9, q:"Sharpe Ratio uses", o:["Total Risk","Beta","Sales","Tax"], a:0 },
{ c:9, q:"Treynor Ratio uses", o:["Beta","Standard Deviation","Dividend","Face Value"], a:0 },
{ c:9, q:"Jensen Measure is based on", o:["Alpha","NAV","Dividend","Book Value"], a:0 },
{ c:9, q:"Higher Sharpe Ratio indicates", o:["Better Performance","Poor Performance","Higher Tax","Lower Return"], a:0 },
{ c:9, q:"Treynor ratio measures return per unit of", o:["Systematic Risk","Total Risk","Liquidity","Credit Risk"], a:0 },
{ c:9, q:"Portfolio revision means", o:["Changing investment mix","Selling everything","Buying gold only","Closing account"], a:0 },
{ c:9, q:"Rebalancing portfolio helps in", o:["Maintaining desired asset allocation","Increasing taxes","Reducing dividends","Avoiding investments"], a:0 },
{ c:9, q:"Benchmark is used for", o:["Performance Comparison","Tax Payment","Loan Approval","Audit"], a:0 },
{ c:9, q:"Portfolio evaluation should be", o:["Periodic","Once in life","Never","Daily compulsory"], a:0 },
{ c:9, q:"Risk-adjusted return is measured using", o:["Sharpe and Treynor","EPS","P/E","NAV"], a:0 },
{ c:9, q:"Benchmark portfolio should be", o:["Comparable","Random","Unrelated","Foreign only"], a:0 },
{ c:9, q:"Jensen Alpha compares actual return with", o:["CAPM Return","Dividend","Book Value","NAV"], a:0 },
{ c:9, q:"Positive Jensen Alpha indicates", o:["Superior Performance","Inferior Performance","Loss","No Return"], a:0 },
{ c:9, q:"Portfolio manager aims to", o:["Maximize Risk Adjusted Return","Increase Taxes","Reduce Sales","Increase Borrowings"], a:0 },
{ c:9, q:"Performance evaluation is useful for", o:["Investment Decisions","GST Filing","Salary Calculation","Inventory Control"], a:0 },
{ c:10, q:"EMH was proposed by", o:["Eugene Fama","Sharpe","Keynes","Marshall"], a:0 },
{ c:10, q:"Weak form efficiency reflects", o:["Past Price Information","Private Information","Inside Information","Government Policy"], a:0 },
{ c:10, q:"Semi-strong form includes", o:["Public Information","Private Information","Rumours","Insider Trading"], a:0 },
{ c:10, q:"Strong form assumes", o:["All Information","Only Public Information","Only Price Data","Only Accounting Data"], a:0 },
{ c:10, q:"In efficient markets abnormal returns are", o:["Not consistently possible","Guaranteed","Very easy","Permanent"], a:0 },
{ c:10, q:"Technical analysis is ineffective under", o:["Weak Form EMH","Strong Form only","Semi Strong only","None"], a:0 },
{ c:10, q:"Fundamental analysis is ineffective under", o:["Semi Strong EMH","Weak EMH","Random Walk only","None"], a:0 },
{ c:10, q:"Random Walk Theory supports", o:["Market Efficiency","Market Failure","Tax Planning","Budgeting"], a:0 },
{ c:10, q:"Insider information is reflected in", o:["Strong Form","Weak Form","Semi Strong","None"], a:0 },
{ c:10, q:"EMH mainly relates to", o:["Capital Market","Labour Market","Commodity Market","Forex Only"], a:0 },
{ c:10, q:"Market prices reflect", o:["Available Information","Rumours Only","Government Orders","Tax Rates"], a:0 },
{ c:10, q:"Semi Strong EMH immediately reflects", o:["Public Announcements","Private Calls","Rumours","Predictions"], a:0 },
{ c:10, q:"Weak form rejects usefulness of", o:["Chart Analysis","Fundamental Analysis","Ratio Analysis","SWOT"], a:0 },
{ c:10, q:"Strong form efficiency assumes even", o:["Insider Information is reflected","No dividends","No profits","No investors"], a:0 },
{ c:10, q:"EMH promotes", o:["Fair Pricing","Price Manipulation","Insider Trading","Speculation"], a:0 },
{ c:11, q:"Risk arising due to changes in market prices is called", o:["Market Risk","Credit Risk","Operational Risk","Legal Risk"], a:0 },
{ c:11, q:"Failure of borrower to repay loan results in", o:["Credit Risk","Market Risk","Liquidity Risk","Settlement Risk"], a:0 },
{ c:11, q:"Liquidity risk refers to", o:["Inability to convert assets into cash quickly","Default by borrower","Interest rate increase","Currency fluctuation"], a:0 },
{ c:11, q:"Interest rate risk mainly affects", o:["Debt Securities","Equity Shares","Inventory","Fixed Assets"], a:0 },
{ c:11, q:"Operational risk arises due to", o:["Failure of systems and processes","Inflation","Exchange rates","Taxation"], a:0 },
{ c:11, q:"Systematic risk cannot be reduced by", o:["Diversification","Portfolio Revision","Asset Allocation","Investment Planning"], a:0 },
{ c:11, q:"Business risk arises because of", o:["Operating activities","Borrowings","Taxation","Foreign Exchange"], a:0 },
{ c:11, q:"Financial risk mainly arises from", o:["Use of debt","Increase in sales","Inventory","Cash"], a:0 },
{ c:11, q:"Inflation risk reduces", o:["Purchasing Power","Sales","Assets","Liabilities"], a:0 },
{ c:11, q:"Country risk mainly affects", o:["International Investments","Domestic Salaries","Inventory","Depreciation"], a:0 },
{ c:11, q:"Political instability increases", o:["Country Risk","Liquidity Risk","Business Risk","Inventory Risk"], a:0 },
{ c:11, q:"Default risk is highest in", o:["Low-rated Bonds","Treasury Bills","Government Securities","Treasury Bonds"], a:0 },
{ c:11, q:"Risk management aims to", o:["Reduce potential losses","Eliminate profit","Increase tax","Reduce revenue"], a:0 },
{ c:11, q:"Hedging is mainly used to", o:["Reduce Risk","Increase Risk","Increase Dividend","Reduce Sales"], a:0 },
{ c:11, q:"Diversification mainly reduces", o:["Unsystematic Risk","Market Risk","Interest Rate Risk","Inflation Risk"], a:0 },
{ c:12, q:"A derivative derives its value from", o:["Underlying Asset","Cash","Sales","Profit"], a:0 },
{ c:12, q:"Forward contract is traded", o:["OTC","Stock Exchange","SEBI","RBI"], a:0 },
{ c:12, q:"Futures contracts are traded on", o:["Organized Exchanges","OTC","Banks","Companies"], a:0 },
{ c:12, q:"Option gives the buyer", o:["Right but not obligation","Obligation only","Ownership","Dividend"], a:0 },
{ c:12, q:"Call option gives right to", o:["Buy","Sell","Lease","Borrow"], a:0 },
{ c:12, q:"Put option gives right to", o:["Sell","Buy","Exchange","Mortgage"], a:0 },
{ c:12, q:"Option premium is paid by", o:["Buyer","Seller","Exchange","Broker"], a:0 },
{ c:12, q:"Future contracts are marked to market", o:["Daily","Monthly","Quarterly","Yearly"], a:0 },
{ c:12, q:"Margin is compulsory in", o:["Futures","Forward","Swap","Spot"], a:0 },
{ c:12, q:"Swap is an agreement to", o:["Exchange Cash Flows","Exchange Shares","Buy Gold","Sell Bonds"], a:0 },
{ c:12, q:"Currency futures help in", o:["Managing Exchange Risk","Increasing Tax","Reducing Sales","Increasing Inventory"], a:0 },
{ c:12, q:"Interest rate swaps exchange", o:["Interest Obligations","Shares","Dividends","Inventory"], a:0 },
{ c:12, q:"Derivatives are mainly used for", o:["Hedging","Increasing Inflation","Tax Collection","Accounting"], a:0 },
{ c:12, q:"Speculators primarily seek", o:["Profit from Price Changes","Stable Income","Tax Savings","Inventory"], a:0 },
{ c:12, q:"Arbitrage means", o:["Riskless Profit","Guaranteed Loss","Long-term Investment","Dividend Planning"], a:0 },
{ c:13, q:"Globalization has increased", o:["International Capital Flows","Inflation","Tax Rates","Inventory"], a:0 },
{ c:13, q:"IMF stands for", o:["International Monetary Fund","Indian Monetary Fund","International Market Forum","Investment Market Fund"], a:0 },
{ c:13, q:"World Bank mainly finances", o:["Development Projects","Share Markets","Mutual Funds","Insurance"], a:0 },
{ c:13, q:"International financial markets facilitate", o:["Cross-border Investments","GST Collection","Inventory Management","Payroll"], a:0 },
{ c:13, q:"Eurobond is issued", o:["Outside the country of currency denomination","Only in Europe","Only in USA","Only in India"], a:0 },
{ c:13, q:"Foreign Direct Investment means", o:["Investment with control","Portfolio Investment","Government Grant","Tax Payment"], a:0 },
{ c:13, q:"Foreign Portfolio Investment mainly involves", o:["Investment in Securities","Buying Factories","Setting up Plants","Land Purchase"], a:0 },
{ c:13, q:"ADR stands for", o:["American Depository Receipt","Asian Deposit Report","Annual Deposit Receipt","American Debt Receipt"], a:0 },
{ c:13, q:"GDR stands for", o:["Global Depository Receipt","General Deposit Receipt","Government Debt Receipt","Global Debt Reserve"], a:0 },
{ c:13, q:"International diversification helps in", o:["Risk Reduction","Tax Increase","Inventory Control","Sales Promotion"], a:0 },
{ c:13, q:"Exchange rates influence", o:["International Trade","Local Salaries","Depreciation","Inventory"], a:0 },
{ c:13, q:"Cross-border financing provides", o:["Access to Global Capital","Tax Exemption","Government Subsidy","Inventory"], a:0 },
{ c:13, q:"International liquidity is supported by", o:["IMF","SEBI","RBI","IRDAI"], a:0 },
{ c:13, q:"Global capital market consists of", o:["Debt and Equity Markets","Only Equity","Only Debt","Commodity Market"], a:0 },
{ c:13, q:"International finance focuses on", o:["Cross-border Financial Decisions","Domestic Accounting","GST","Payroll"], a:0 },
{ c:14, q:"Forex market deals in", o:["Currencies","Shares","Gold","Real Estate"], a:0 },
{ c:14, q:"Exchange rate means", o:["Price of one currency in terms of another","Interest Rate","Inflation Rate","Tax Rate"], a:0 },
{ c:14, q:"Spot exchange transaction settles generally within", o:["2 Business Days","30 Days","60 Days","90 Days"], a:0 },
{ c:14, q:"Forward exchange contract is used for", o:["Future Currency Exchange","Spot Settlement","GST","Tax"], a:0 },
{ c:14, q:"Direct quotation expresses", o:["Domestic Currency per Unit of Foreign Currency","Foreign Currency per Domestic Currency","Interest Rate","Dividend"], a:0 },
{ c:14, q:"Appreciation of domestic currency makes imports", o:["Cheaper","Costlier","Unchanged","Illegal"], a:0 },
{ c:14, q:"Depreciation of domestic currency makes exports", o:["More Competitive","Less Competitive","Unchanged","Impossible"], a:0 },
{ c:14, q:"Major participants in forex market include", o:["Banks","Individuals","Corporates","All of these"], a:3 },
{ c:14, q:"Cross exchange rate is calculated using", o:["Two Different Currency Rates","Inflation","Interest","Tax"], a:0 },
{ c:14, q:"Arbitrage in forex market aims at", o:["Risk-free Profit","Loss","Tax Planning","Investment"], a:0 },
{ c:14, q:"Interbank forex market consists of", o:["Commercial Banks","Retail Customers","Government Employees","Mutual Funds"], a:0 },
{ c:14, q:"Currency quotation may be", o:["Direct or Indirect","Only Direct","Only Indirect","Only Spot"], a:0 },
{ c:14, q:"Foreign exchange reserves are maintained by", o:["Central Bank","SEBI","IRDAI","Stock Exchange"], a:0 },
{ c:14, q:"Spot market is used for", o:["Immediate Delivery","Future Delivery","Long-term Lease","Insurance"], a:0 },
{ c:14, q:"Forward premium arises when", o:["Forward Rate > Spot Rate","Forward Rate < Spot Rate","Rates Equal","No Quote"], a:0 },
{ c:15, q:"Transaction exposure arises due to", o:["Foreign currency receivables and payables","Fixed assets","Inventory valuation","Domestic sales"], a:0 },
{ c:15, q:"Translation exposure is also known as", o:["Accounting Exposure","Economic Exposure","Operating Exposure","Market Exposure"], a:0 },
{ c:15, q:"Economic exposure affects", o:["Future cash flows","Past transactions","Accounting records only","Inventory only"], a:0 },
{ c:15, q:"A forward contract is primarily used for", o:["Hedging exchange risk","Speculation only","Tax planning","Increasing leverage"], a:0 },
{ c:15, q:"Natural hedging means", o:["Matching foreign currency inflows and outflows","Buying options","Using swaps","Taking insurance"], a:0 },
{ c:15, q:"Currency futures are traded on", o:["Recognized Exchanges","OTC Market","Banks only","RBI"], a:0 },
{ c:15, q:"Currency options provide", o:["Right but not obligation","Compulsory exchange","Guaranteed profit","Fixed exchange rate"], a:0 },
{ c:15, q:"Money market hedge involves", o:["Borrowing and lending in different currencies","Buying shares","Purchasing gold","Leasing assets"], a:0 },
{ c:15, q:"Leading strategy means", o:["Making payment earlier","Delaying payment","Cancelling contract","Ignoring exposure"], a:0 },
{ c:15, q:"Lagging strategy means", o:["Delaying payment or receipt","Making early payment","Buying options","Selling futures"], a:0 },
{ c:15, q:"Currency swap exchanges", o:["Principal and interest in different currencies","Only principal","Only interest","Only dividends"], a:0 },
{ c:15, q:"The main objective of hedging is", o:["Reduce exchange risk","Increase speculation","Earn arbitrage profit","Increase leverage"], a:0 },
{ c:15, q:"Foreign exchange exposure exists when", o:["Cash flows are denominated in foreign currency","Only domestic sales exist","No imports or exports","Only cash sales"], a:0 },
{ c:15, q:"An exporter expecting foreign currency receipts usually", o:["Sells forward","Buys forward","Buys call option","Borrows locally"], a:0 },
{ c:15, q:"An importer expecting foreign currency payment generally", o:["Buys forward","Sells forward","Sells call option","Buys domestic currency"], a:0 },
{ c:16, q:"Digital finance primarily uses", o:["Technology to deliver financial services","Only paper documents","Only cash transactions","Only bank branches"], a:0 },
{ c:16, q:"UPI stands for", o:["Unified Payments Interface","Universal Payment Integration","Unique Payment Interface","Unified Processing Interface"], a:0 },
{ c:16, q:"NEFT is mainly used for", o:["Electronic fund transfer","Cash withdrawal","Cheque printing","Loan sanction"], a:0 },
{ c:16, q:"RTGS is generally used for", o:["High value real-time transfers","Mobile recharge","ATM withdrawal","Cheque deposit"], a:0 },
{ c:16, q:"IMPS enables fund transfer", o:["24×7","Only during banking hours","Only on working days","Only through branch"], a:0 },
{ c:16, q:"A digital wallet stores", o:["Payment information electronically","Physical cash","Gold","Shares"], a:0 },
{ c:16, q:"FinTech refers to", o:["Financial Technology","Final Technology","Finance Tax","Financial Trading"], a:0 },
{ c:16, q:"Blockchain technology is known for", o:["Decentralized ledger","Centralized database","Cash transactions","Cheque clearing"], a:0 },
{ c:16, q:"Cryptocurrency is based on", o:["Blockchain","Cheque","Gold Standard","Paper Currency"], a:0 },
{ c:16, q:"KYC stands for", o:["Know Your Customer","Know Your Cash","Keep Your Credit","Know Your Capital"], a:0 },
{ c:16, q:"Cyber security in digital finance aims to", o:["Protect financial data","Increase taxation","Reduce profits","Issue shares"], a:0 },
{ c:16, q:"Digital banking reduces", o:["Paper-based transactions","Interest rates","Bank capital","Foreign exchange"], a:0 },
{ c:16, q:"QR code payments are commonly used in", o:["UPI Transactions","Cheque Clearing","RTGS Settlement","Loan Approval"], a:0 },
{ c:16, q:"Two-factor authentication improves", o:["Security","Liquidity","Profitability","Taxation"], a:0 },
{ c:16, q:"The regulator of payment systems in India is", o:["RBI","SEBI","IRDAI","PFRDA"], a:0 },
];
